/**
 * starfield.js — Interactive Star Viewer (Application Shell)
 *
 * Real-time night sky from Fontana, CA (34.09°N, 117.44°W).
 * Camera-frame projection in horizontal space — flat horizon at all azimuths.
 *
 * Architecture:
 *   js/sky/             — Pure astronomy math (time, projection, ephemeris). No DOM.
 *   js/viewer/          — Feature modules: rendering, input, search, controls.
 *   js/starfield.js     — Application shell: state, init, render loop.
 *   css/starfield.css   — All viewer UI styles (separate from portfolio styles).
 *
 * Data: data/stars.json (generated by scripts/process_stars.py)
 */

// --- Astronomy layer (pure math, no DOM) ---
import { fovToScale }      from './sky/projection.js';
import { lst }             from './sky/time.js';
// planet ephemeris managed by viewer/controls.js

// --- Viewer modules ---
import { LON_LA, FOV_DEFAULT, FOV_MIN, FOV_MAX, ALT_MIN, ALT_MAX, reducedMotion } from './viewer/config.js';
import { fovMagLimit, bvToColor, magToRadius, magToAlpha } from './viewer/visual.js';
import { buildViewFrame, precomputeEq, unprojectScreen, applyDragRotation } from './viewer/camera.js';
import { advanceTime, getTimeState, setupTimeControls, updateEphemeris, getCachedPlanets, getCachedSun, getCachedMoon, setSpeed, resetTime } from './viewer/controls.js';
import { updatePopup } from './viewer/popup.js';
import { buildSearchIndex, setupSearch } from './viewer/search.js';
import { setupInput } from './viewer/input.js';

// --- Render layers ---
import { initMilkyWay, renderMilkyWay, renderTwilight, renderAltAzGrid, renderEqGrid, renderEcliptic, renderZodiacBand, renderHorizon } from './viewer/render-background.js';
import { renderStars, renderDSOs, renderSun, renderMoon, renderPlanets } from './viewer/render-objects.js';
import { renderConstellationLines, renderConstellationHighlight, renderSelection, renderCardinals, renderLabels } from './viewer/render-overlays.js';

// --- DOM (may be null if elements aren't in the page yet) ---

const canvas      = document.getElementById('sky-canvas');
const ctx         = canvas ? canvas.getContext('2d') : null;
const infoEl      = document.getElementById('info');
const clockTimeEl = document.getElementById('clock-time');
const clockDateEl = document.getElementById('clock-date');
const popupEl     = document.getElementById('object-popup');

// --- State ---

let data = null;

const view = { az: 180.0, alt: 45.0, fov: FOV_DEFAULT };
const drag = { active: false, prevX: 0, prevY: 0, startX: 0, startY: 0, startTime: 0 };
const overlays = { altAzGrid: false, eqGrid: false, ecliptic: true };
const toggles  = { constellations: true };

let selectedObject = null;
let hoveredConst   = null;
let clickedConst   = null;
let constFadeAlphas = {};
let _lastFrameTime = performance.now();

let viewTarget = null;

let W = 0, H = 0, cx = 0, cy = 0;

// Screen position buffers for hit testing (filled each frame by render modules)
let starScreenBuf = null;
let starScreenCount = 0;
let planetScreenBuf = [];
let moonScreenPos = null;
let constLabelScreen = [];
let dsoScreenBuf = [];

// Portfolio mode: passive background (reduced layers, no interaction)
let portfolioMode = true;
let _frameId = null;

// Lookup tables (built at init)
let starNameLookup = null;
let hipToConst = null;
let constByAbbr = null;

// --- Canvas sizing ---

function resize() {
  const dpr = window.devicePixelRatio || 1;
  W = window.innerWidth;
  H = window.innerHeight;
  canvas.width  = Math.round(W * dpr);
  canvas.height = Math.round(H * dpr);
  canvas.style.width  = W + 'px';
  canvas.style.height = H + 'px';
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  cx = W / 2;
  cy = H / 2;
}

// --- Popup delegation ---

function callUpdatePopup() {
  updatePopup(popupEl, selectedObject, clickedConst, {
    cachedPlanets: getCachedPlanets(), cachedMoon: getCachedMoon(),
    constByAbbr, hipToConst, starNameLookup,
    timeOffsetMs: getTimeState().timeOffsetMs,
  });
}

// --- Clock ---

const clockFmt = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/Los_Angeles',
  hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false,
});
const dateFmt = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/Los_Angeles',
  year: 'numeric', month: 'short', day: '2-digit', weekday: 'short',
});

let _lastClockSec = -1;
let _lastClockSpeed = null;
function updateClock() {
  if (!clockTimeEl) return;
  const ts = getTimeState();
  const simTime = new Date(Date.now() + ts.timeOffsetMs);
  const s = simTime.getSeconds();
  if (s === _lastClockSec && ts.timeSpeed === _lastClockSpeed) return;
  _lastClockSec = s;
  _lastClockSpeed = ts.timeSpeed;
  clockTimeEl.textContent = clockFmt.format(simTime);
  clockDateEl.textContent = dateFmt.format(simTime);
  const speedEl = document.getElementById('time-speed');
  if (speedEl) {
    if (ts.timeSpeed === 0) speedEl.textContent = 'Paused';
    else if (ts.timeSpeed === 1) speedEl.textContent = '';
    else speedEl.textContent = `${ts.timeSpeed}\u00d7`;
  }
  const liveEl = document.getElementById('live-indicator');
  if (liveEl) {
    const isLive = ts.timeSpeed === 1 && Math.abs(ts.timeOffsetMs) < 1000;
    liveEl.classList.toggle('live', isLive);
    liveEl.classList.toggle('not-live', !isLive);
  }
}

// --- Info panel ---

let _lastInfoKey = '';
function updateInfo() {
  if (!infoEl) return;
  const key = `${view.fov}|${overlays.altAzGrid}|${overlays.eqGrid}|${overlays.ecliptic}|${toggles.constellations}`;
  if (key === _lastInfoKey) return;
  _lastInfoKey = key;
  const magLimit = fovMagLimit(view.fov);
  const g = (on, key) => on ? `<span style="color:#4f4">[${key}]</span>` : `<span style="color:#555">[${key}]</span>`;
  infoEl.innerHTML =
    `<b>Star Viewer — Fontana, CA</b><br>` +
    `FOV: ${view.fov.toFixed(1)}° | Mag: ${magLimit.toFixed(1)}<br>` +
    g(overlays.altAzGrid, 'G') + ' ' + g(overlays.eqGrid, 'Q') + ' ' +
    g(overlays.ecliptic, 'E') + ' ' + g(toggles.constellations, 'C');
}

// --- Main render ---

// --- Cursor-anchored zoom ---
// Change FOV while keeping the sky point under (focusX, focusY) fixed:
// unproject the focus pixel before and after the FOV change, then pan the
// view by the difference.
function applyZoom(focusX, focusY, newFov) {
  newFov = Math.max(FOV_MIN, Math.min(FOV_MAX, newFov));
  const jd = (Date.now() + getTimeState().timeOffsetMs) / 86400000 + 2440587.5;
  const vfNow = buildViewFrame(view.alt, view.az, lst(jd, LON_LA));
  const half = Math.min(cx, cy);
  const before = unprojectScreen(focusX, focusY, cx, cy, fovToScale(view.fov, half), vfNow);
  view.fov = newFov;
  const after = unprojectScreen(focusX, focusY, cx, cy, fovToScale(newFov, half), vfNow);
  const dAz = ((before.az - after.az + 540) % 360) - 180;
  view.az = ((view.az + dAz) % 360 + 360) % 360;
  view.alt = Math.max(ALT_MIN, Math.min(ALT_MAX, view.alt + (before.alt - after.alt)));
}

// --- Drag inertia ---
// A released fling keeps panning with exponential decay. Runs in render()
// so it shares the interactive frame rate; cleared by any new pointer-down.
let _inertia = null; // { vx, vy } in px/s

function startInertia(vx, vy) {
  _inertia = { vx, vy };
}
function stopInertia() {
  _inertia = null;
}

// --- Offscreen layer cache (exploration idle path) ---
// Two full-size canvases: "under" holds everything painted below the stars
// (Milky Way, twilight, grids, ecliptic/zodiac, DSO bases, constellation
// lines); "over" holds the labels painted above everything. Both depend only
// on (view, size, lst-bucket, overlay flags), so at rest they are stamped
// with two drawImage calls instead of ~3-13k projections + 115 fillTexts.

const _layerCache = { key: '', under: null, underCtx: null, over: null, overCtx: null, dsoBuf: [], labelBuf: [] };

function layerCacheKey(lstDeg) {
  // lst bucketed at 0.005° (~0.05px at default FOV): live sidereal drift
  // invalidates the cache every ~1.2s rather than every frame.
  return view.az.toFixed(3) + ',' + view.alt.toFixed(3) + ',' + view.fov.toFixed(3) +
    ',' + W + 'x' + H + ',' + Math.round(lstDeg / 0.005) +
    ',' + overlays.altAzGrid + overlays.eqGrid + overlays.ecliptic + toggles.constellations;
}

function rebuildLayerCache(key, lstDeg, scale, vf) {
  const dpr = window.devicePixelRatio || 1;
  const pw = Math.round(W * dpr), ph = Math.round(H * dpr);
  if (!_layerCache.under) {
    _layerCache.under = document.createElement('canvas');
    _layerCache.over  = document.createElement('canvas');
    _layerCache.underCtx = _layerCache.under.getContext('2d');
    _layerCache.overCtx  = _layerCache.over.getContext('2d');
  }
  for (const c of [_layerCache.under, _layerCache.over]) {
    if (c.width !== pw || c.height !== ph) { c.width = pw; c.height = ph; }
  }

  const uc = _layerCache.underCtx, oc = _layerCache.overCtx;
  uc.setTransform(dpr, 0, 0, dpr, 0, 0);
  oc.setTransform(dpr, 0, 0, dpr, 0, 0);
  uc.clearRect(0, 0, W, H);
  oc.clearRect(0, 0, W, H);

  const rcU = { ctx: uc, cx, cy, scale, vf, fov: view.fov };
  renderMilkyWay(rcU);
  renderTwilight(rcU, lstDeg, getCachedSun());
  if (overlays.altAzGrid) renderAltAzGrid(rcU);
  if (overlays.eqGrid) renderEqGrid(rcU);
  if (overlays.ecliptic) { renderZodiacBand(rcU); renderEcliptic(rcU); }
  _layerCache.dsoBuf = renderDSOs(rcU, data.dsos, null); // pulse drawn live
  renderConstellationLines(rcU, data.constellations, constFadeAlphas, toggles.constellations);

  const rcO = { ctx: oc, cx, cy, scale, vf, fov: view.fov };
  _layerCache.labelBuf = renderLabels(rcO, data.constellations, data.dsos, constFadeAlphas, toggles.constellations);

  _layerCache.key = key;
}

// The cached DSO layer is drawn without selection state; the pulsing ring for
// a selected DSO animates live on top of it.
function drawSelectedDsoPulse() {
  if (!selectedObject || selectedObject.type !== 'dso') return;
  const d = _layerCache.dsoBuf.find(e => e.name === selectedObject.name);
  if (!d) return;
  const pulse = reducedMotion ? 1.0 : 0.7 + 0.3 * Math.sin(performance.now() * 0.003);
  ctx.strokeStyle = `rgba(180,180,255,${pulse})`;
  ctx.lineWidth = 1.5;
  ctx.beginPath(); ctx.arc(d.px, d.py, d.screenR + 4, 0, Math.PI * 2); ctx.stroke();
}

function render() {
  if (!data || !ctx) return;
  const jd = advanceTime();
  const lstDeg = lst(jd, LON_LA);
  updateEphemeris(jd);

  // Per-frame timing
  const now = performance.now();
  const dt = Math.min((now - _lastFrameTime) / 1000, 0.1);
  _lastFrameTime = now;

  // Animated pan toward target
  if (viewTarget) {
    const speed = 5;
    const dAz = ((viewTarget.az - view.az + 540) % 360) - 180;
    const dAlt = viewTarget.alt - view.alt;
    if (Math.abs(dAz) < 0.1 && Math.abs(dAlt) < 0.1) {
      view.az = viewTarget.az; view.alt = viewTarget.alt;
      viewTarget = null;
    } else {
      view.az = ((view.az + dAz * speed * dt) % 360 + 360) % 360;
      view.alt = Math.max(ALT_MIN, Math.min(ALT_MAX, view.alt + dAlt * speed * dt));
    }
  }

  // Fling inertia — decays exponentially after a released drag
  if (_inertia) {
    const degPerPx = view.fov / Math.min(W, H);
    const nv = applyDragRotation(view.alt, view.az, _inertia.vx * dt, _inertia.vy * dt, degPerPx);
    view.alt = nv.alt; view.az = nv.az;
    const decay = Math.exp(-dt / 0.4);
    _inertia.vx *= decay; _inertia.vy *= decay;
    if (Math.hypot(_inertia.vx, _inertia.vy) < 15) _inertia = null;
  }

  // Build camera frame and render context
  const vf = buildViewFrame(view.alt, view.az, lstDeg);
  const scale = fovToScale(view.fov, Math.min(cx, cy));
  const rc = { ctx, cx, cy, scale, vf, fov: view.fov };

  // Constellation fade animation — hovered and clicked both stay highlighted
  const fadeSpeed = dt / 0.3;
  for (const abbr in constFadeAlphas) {
    if (abbr === hoveredConst || abbr === clickedConst) continue;
    constFadeAlphas[abbr] -= fadeSpeed;
    if (constFadeAlphas[abbr] <= 0) delete constFadeAlphas[abbr];
  }
  if (hoveredConst) {
    constFadeAlphas[hoveredConst] = Math.min(1, (constFadeAlphas[hoveredConst] || 0) + fadeSpeed);
  }
  if (clickedConst && clickedConst !== hoveredConst) {
    constFadeAlphas[clickedConst] = Math.min(1, (constFadeAlphas[clickedConst] || 0) + fadeSpeed);
  }

  // Lazy-allocate star screen buffer
  if (!starScreenBuf || starScreenBuf.length < data.stars.length * 3) {
    starScreenBuf = new Float32Array(data.stars.length * 3);
  }

  // Clear
  ctx.fillStyle = '#050510';
  ctx.fillRect(0, 0, W, H);

  // Exploration idle path: static layers (Milky Way, grids, ecliptic, DSO
  // bases, constellation lines, labels) depend only on view+time — stamp
  // them from offscreen canvases and render just the dynamic objects live.
  // Any interaction (drag, pan target, fast time, constellation fades)
  // bypasses the cache and draws everything directly.
  let anyFade = false;
  for (const k in constFadeAlphas) { anyFade = true; break; }
  const cacheable = !portfolioMode && !drag.active && viewTarget === null &&
                    _inertia === null && !anyFade &&
                    Math.abs(getTimeState().timeSpeed) <= 1;

  if (cacheable) {
    const key = layerCacheKey(lstDeg);
    if (_layerCache.key !== key) rebuildLayerCache(key, lstDeg, scale, vf);
    ctx.drawImage(_layerCache.under, 0, 0, W, H);
    dsoScreenBuf = _layerCache.dsoBuf;

    starScreenCount = renderStars(rc, data.stars, starScreenBuf, false);
    renderSelection(rc, selectedObject);
    drawSelectedDsoPulse();
    renderHorizon(rc);
    renderCardinals(rc);
    planetScreenBuf = renderPlanets(rc, getCachedPlanets());
    renderSun(rc, getCachedSun());
    moonScreenPos = renderMoon(rc, getCachedMoon(), getCachedSun());
    ctx.drawImage(_layerCache.over, 0, 0, W, H);
    constLabelScreen = _layerCache.labelBuf;
  } else {
    // Background layers
    if (!portfolioMode) renderMilkyWay(rc);
    if (!portfolioMode) renderTwilight(rc, lstDeg, getCachedSun());
    if (!portfolioMode && overlays.altAzGrid) renderAltAzGrid(rc);
    if (!portfolioMode && overlays.eqGrid) renderEqGrid(rc);
    if (!portfolioMode && overlays.ecliptic) { renderZodiacBand(rc); renderEcliptic(rc); }

    // Sky objects (return screen buffers for hit testing)
    if (!portfolioMode) dsoScreenBuf = renderDSOs(rc, data.dsos, selectedObject);
    renderConstellationLines(rc, data.constellations, constFadeAlphas, toggles.constellations);
    starScreenCount = renderStars(rc, data.stars, starScreenBuf, portfolioMode);
    if (!portfolioMode) renderConstellationHighlight(rc, constFadeAlphas, constByAbbr, data.hip);
    if (!portfolioMode) renderSelection(rc, selectedObject);
    if (!portfolioMode) renderHorizon(rc);
    if (!portfolioMode) renderCardinals(rc);
    planetScreenBuf = renderPlanets(rc, getCachedPlanets());
    renderSun(rc, getCachedSun());
    moonScreenPos = renderMoon(rc, getCachedMoon(), getCachedSun());
    if (!portfolioMode) constLabelScreen = renderLabels(rc, data.constellations, data.dsos, constFadeAlphas, toggles.constellations);
  }

  // UI updates (skip in portfolio mode)
  if (!portfolioMode) {
    updateInfo();
    updateClock();
    callUpdatePopup();
  }
}

let _lastRenderTime = 0;
let _lastSceneSig = '';

// Cheap scene fingerprint — when it's unchanged and nothing is animating,
// the only frame-to-frame difference is star twinkle / selection pulse.
function sceneSignature() {
  return view.az.toFixed(4) + ',' + view.alt.toFixed(4) + ',' + view.fov.toFixed(3) +
    ',' + W + 'x' + H +
    ',' + (hoveredConst || '') + ',' + (clickedConst || '') +
    ',' + (selectedObject ? (selectedObject.name || selectedObject.type || 's') : '') +
    ',' + overlays.altAzGrid + overlays.eqGrid + overlays.ecliptic + toggles.constellations;
}

function frame(timestamp) {
  _frameId = requestAnimationFrame(frame);
  const elapsed = timestamp - _lastRenderTime;

  if (portfolioMode) {
    // Decorative background: ~10 fps keeps the slow sky drift and twinkle
    // moving in sub-pixel steps (smooth to the eye) at a fraction of full-
    // rate cost. Reduced-motion users keep a static first frame.
    if (_lastRenderTime) {
      if (reducedMotion) return;
      if (elapsed < 100) return;
    }
  } else {
    // Exploration: cap at ~30 fps while interacting (drag/pan/zoom/time/fades
    // — twinkle stays smooth), drop to ~10 fps when the scene is static and
    // only twinkle/pulse animate, and go fully still under reduced motion
    // (twinkle and pulses are already disabled there).
    let anyFade = false;
    for (const k in constFadeAlphas) { anyFade = true; break; }
    // Live time (speed 1) moves the sky sub-pixel per frame — not animation.
    // Only fast time-travel (|speed| > 1) needs the interactive rate.
    const animating = drag.active || viewTarget !== null || anyFade ||
                      _inertia !== null || Math.abs(getTimeState().timeSpeed) > 1;
    const sig = sceneSignature();
    if (animating || sig !== _lastSceneSig) {
      if (elapsed < 33) return;
    } else if (reducedMotion) {
      if (_lastRenderTime) return;
    } else if (elapsed < 100) {
      return;
    }
    _lastSceneSig = sig;
  }

  _lastRenderTime = timestamp;
  render();
}

// --- Init ---

function buildStarNameLookup() {
  starNameLookup = new Map();
  if (data.star_names) {
    for (const hipID of Object.keys(data.star_names)) {
      const pos = data.hip[hipID];
      if (!pos) continue;
      const key = pos[0].toFixed(6) + ',' + pos[1].toFixed(5);
      starNameLookup.set(key, { ...data.star_names[hipID], hipID });
    }
  }
  hipToConst = new Map();
  for (const c of data.constellations) {
    for (const [h1, h2] of c.lines) {
      for (const h of [h1, h2]) {
        const pos = data.hip[String(h)];
        if (pos) hipToConst.set(pos[0].toFixed(6) + ',' + pos[1].toFixed(5), c.abbr);
      }
    }
  }
}

async function init() {
  resize();

  try {
    const resp = await fetch('data/stars.json');
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    data = await resp.json();
  } catch (err) {
    throw new Error(`failed to load star catalog: ${err.message}`);
  }

  data.stars.sort((a, b) => a[2] - b[2]);

  // Precompute each star's constant visual properties once. Color (from B-V
  // index) and base radius/alpha (from magnitude) never change, so the render
  // loop reads these instead of recomputing them every frame.
  //   s[6] = "r,g,b" string   s[7] = radius   s[8] = base alpha
  //   s[9] = full canvas fillStyle — paired with globalAlpha, this makes the
  //          star loop allocation-free (no rgba template string per star)
  //   s[10..12] = sin(dec), cos(dec)cos(ra), cos(dec)sin(ra) — lets the render
  //          loop project with zero trig calls (see camera.js projectStarPre)
  for (const s of data.stars) {
    s[6] = bvToColor(s[3]);
    s[7] = magToRadius(s[2]);
    s[8] = magToAlpha(s[2]);
    s[9] = `rgb(${s[6]})`;
    const pre = precomputeEq(s[0], s[1]);
    s[10] = pre[0]; s[11] = pre[1]; s[12] = pre[2];
  }

  // Constellation line segments store precomputed projection terms for both
  // endpoints (see projectStarPre) — 6 numbers per segment.
  for (const c of data.constellations) {
    c.resolvedLines = [];
    for (const pair of c.lines) {
      const s1 = data.hip[String(pair[0])];
      const s2 = data.hip[String(pair[1])];
      if (s1 && s2) {
        const a = precomputeEq(s1[0], s1[1]);
        const b = precomputeEq(s2[0], s2[1]);
        c.resolvedLines.push([a[0], a[1], a[2], b[0], b[1], b[2]]);
      }
    }
  }

  initMilkyWay(data.milky_way);
  buildStarNameLookup();
  for (const c of data.constellations) {
    c.starCount = new Set(c.lines.flat()).size;
  }
  constByAbbr = new Map(data.constellations.map(c => [c.abbr, c]));

  setSpeed(100); // portfolio mode default: 100x for visible sky motion
  const initJd = (Date.now() + getTimeState().timeOffsetMs) / 86400000 + 2440587.5;
  updateEphemeris(initJd);
  buildSearchIndex(data, getCachedPlanets(), getCachedMoon());
  setupTimeControls();
  setupSearch({
    setViewTarget: (t) => { viewTarget = t; },
    setSelectedObject: (o) => { selectedObject = o; },
    setClickedConst: (c) => { clickedConst = c; },
    getAppState: () => ({ cachedPlanets: getCachedPlanets(), cachedMoon: getCachedMoon(), data, cx, cy }),
  });
}

let _inputReady = false;
function ensureInputSetup() {
  if (_inputReady) return;
  _inputReady = true;
  setupInput(
    { view, drag, overlays, toggles, canvas, getSize: () => ({ W, H }) },
    {
      setViewTarget: (t) => { viewTarget = t; },
      setSelectedObject: (o) => { selectedObject = o; },
      setClickedConst: (c) => { clickedConst = c; },
      setHoveredConst: (h) => { hoveredConst = h; },
      isViewerActive: () => !portfolioMode,
      hasSelection: () => !!(selectedObject || clickedConst),
      applyZoom,
      startInertia,
      stopInertia,
      onResize: resize,
      getScreenState: () => ({
        starScreenBuf, starScreenCount, planetScreenBuf, moonScreenPos,
        constLabelScreen, dsoScreenBuf, data, hipToConst,
      }),
    },
  );
}

export function setPortfolioMode(enabled) {
  portfolioMode = enabled;
  _lastRenderTime = 0; // render one immediate frame in the new mode's layer set
  _lastSceneSig = '';
  if (enabled) {
    selectedObject = null;
    clickedConst = null;
    hoveredConst = null;
    constFadeAlphas = {};
    viewTarget = null;
    canvas.style.cursor = '';
    setSpeed(25);
  } else {
    canvas.style.cursor = 'grab';
    resetTime();
  }
}

export function isPortfolioMode() {
  return portfolioMode;
}

export function startRenderer() {
  if (!_frameId) frame();
}

export function stopRenderer() {
  if (_frameId) { cancelAnimationFrame(_frameId); _frameId = null; }
}

export { init, ensureInputSetup };
