/**
 * starfield.js — Interactive Star Viewer (Application Shell)
 *
 * Real-time night sky from Los Angeles (34.05°N, 118.24°W).
 * Camera-frame projection in horizontal space — flat horizon at all azimuths.
 *
 * Architecture:
 *   js/sky/             — Pure astronomy math (time, projection, ephemeris). No DOM.
 *   js/viewer/          — Feature modules: rendering, input, search, controls.
 *   js/starfield.js     — Application shell: state, init, render loop.
 *   css/starfield.css   — All viewer UI styles (separate from portfolio styles).
 *
 * Data: data/stars.json (generated by scripts/process_stars.py)
 */

// --- Astronomy layer (pure math, no DOM) ---
import { fovToScale }      from './sky/projection.js';
import { lst }             from './sky/time.js';
// planet ephemeris managed by viewer/controls.js

// --- Viewer modules ---
import { LON_LA, FOV_DEFAULT, ALT_MIN, ALT_MAX } from './viewer/config.js';
import { fovMagLimit } from './viewer/visual.js';
import { buildViewFrame } from './viewer/camera.js';
import { advanceTime, getTimeState, setupTimeControls, updateEphemeris, getCachedPlanets, getCachedSun, getCachedMoon } from './viewer/controls.js';
import { updatePopup } from './viewer/popup.js';
import { buildSearchIndex, setupSearch } from './viewer/search.js';
import { setupInput } from './viewer/input.js';

// --- Render layers ---
import { initMilkyWay, renderMilkyWay, renderTwilight, renderAltAzGrid, renderEqGrid, renderEcliptic, renderZodiacBand, renderHorizon } from './viewer/render-background.js';
import { renderStars, renderDSOs, renderSun, renderMoon, renderPlanets } from './viewer/render-objects.js';
import { renderConstellationLines, renderConstellationHighlight, renderSelection, renderCardinals, renderLabels } from './viewer/render-overlays.js';

// --- DOM ---

const canvas   = document.getElementById('sky-canvas');
const ctx      = canvas.getContext('2d');
const infoEl   = document.getElementById('info');
const clockTimeEl = document.getElementById('clock-time');
const clockDateEl = document.getElementById('clock-date');
const popupEl     = document.getElementById('object-popup');

// --- State ---

let data = null;

const view = { az: 180.0, alt: 45.0, fov: FOV_DEFAULT };
const drag = { active: false, prevX: 0, prevY: 0, startX: 0, startY: 0, startTime: 0 };
const overlays = { altAzGrid: false, eqGrid: false, ecliptic: true };
const toggles  = { constellations: true };

let selectedObject = null;
let hoveredConst   = null;
let clickedConst   = null;
let constFadeAlphas = {};
let _lastFrameTime = performance.now();

let viewTarget = null;

let W = 0, H = 0, cx = 0, cy = 0;

// Screen position buffers for hit testing (filled each frame by render modules)
let starScreenBuf = null;
let starScreenCount = 0;
let planetScreenBuf = [];
let moonScreenPos = null;
let constLabelScreen = [];
let dsoScreenBuf = [];

// Lookup tables (built at init)
let starNameLookup = null;
let hipToConst = null;
let constByAbbr = null;

// --- Canvas sizing ---

function resize() {
  const dpr = window.devicePixelRatio || 1;
  W = window.innerWidth;
  H = window.innerHeight;
  canvas.width  = Math.round(W * dpr);
  canvas.height = Math.round(H * dpr);
  canvas.style.width  = W + 'px';
  canvas.style.height = H + 'px';
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  cx = W / 2;
  cy = H / 2;
}

// --- Popup delegation ---

function callUpdatePopup() {
  updatePopup(popupEl, selectedObject, clickedConst, {
    cachedPlanets: getCachedPlanets(), cachedMoon: getCachedMoon(),
    constByAbbr, hipToConst, starNameLookup,
    timeOffsetMs: getTimeState().timeOffsetMs,
  });
}

// --- Clock ---

const clockFmt = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/Los_Angeles',
  hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false,
});
const dateFmt = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/Los_Angeles',
  year: 'numeric', month: 'short', day: '2-digit', weekday: 'short',
});

let _lastClockSec = -1;
let _lastClockSpeed = null;
function updateClock() {
  if (!clockTimeEl) return;
  const ts = getTimeState();
  const simTime = new Date(Date.now() + ts.timeOffsetMs);
  const s = simTime.getSeconds();
  if (s === _lastClockSec && ts.timeSpeed === _lastClockSpeed) return;
  _lastClockSec = s;
  _lastClockSpeed = ts.timeSpeed;
  clockTimeEl.textContent = clockFmt.format(simTime);
  clockDateEl.textContent = dateFmt.format(simTime);
  const speedEl = document.getElementById('time-speed');
  if (speedEl) {
    if (ts.timeSpeed === 0) speedEl.textContent = 'Paused';
    else if (ts.timeSpeed === 1) speedEl.textContent = '';
    else speedEl.textContent = `${ts.timeSpeed}\u00d7`;
  }
  const liveEl = document.getElementById('live-indicator');
  if (liveEl) {
    const isLive = ts.timeSpeed === 1 && Math.abs(ts.timeOffsetMs) < 1000;
    liveEl.classList.toggle('live', isLive);
    liveEl.classList.toggle('not-live', !isLive);
  }
}

// --- Info panel ---

function updateInfo() {
  const magLimit = fovMagLimit(view.fov);
  const g = (on, key) => on ? `<span style="color:#4f4">[${key}]</span>` : `<span style="color:#555">[${key}]</span>`;
  infoEl.innerHTML =
    `<b>Star Viewer — Los Angeles</b><br>` +
    `FOV: ${view.fov.toFixed(1)}° | Mag: ${magLimit.toFixed(1)}<br>` +
    g(overlays.altAzGrid, 'G') + ' ' + g(overlays.eqGrid, 'Q') + ' ' +
    g(overlays.ecliptic, 'E') + ' ' + g(toggles.constellations, 'C');
}

// --- Main render ---

function render() {
  const jd = advanceTime();
  const lstDeg = lst(jd, LON_LA);
  updateEphemeris(jd);

  // Per-frame timing
  const now = performance.now();
  const dt = Math.min((now - _lastFrameTime) / 1000, 0.1);
  _lastFrameTime = now;

  // Animated pan toward target
  if (viewTarget) {
    const speed = 5;
    const dAz = ((viewTarget.az - view.az + 540) % 360) - 180;
    const dAlt = viewTarget.alt - view.alt;
    if (Math.abs(dAz) < 0.1 && Math.abs(dAlt) < 0.1) {
      view.az = viewTarget.az; view.alt = viewTarget.alt;
      viewTarget = null;
    } else {
      view.az = ((view.az + dAz * speed * dt) % 360 + 360) % 360;
      view.alt = Math.max(ALT_MIN, Math.min(ALT_MAX, view.alt + dAlt * speed * dt));
    }
  }

  // Build camera frame and render context
  const vf = buildViewFrame(view.alt, view.az, lstDeg);
  const scale = fovToScale(view.fov, Math.min(cx, cy));
  const rc = { ctx, cx, cy, scale, vf, fov: view.fov };

  // Constellation fade animation — hovered and clicked both stay highlighted
  const fadeSpeed = dt / 0.3;
  for (const abbr in constFadeAlphas) {
    if (abbr === hoveredConst || abbr === clickedConst) continue;
    constFadeAlphas[abbr] -= fadeSpeed;
    if (constFadeAlphas[abbr] <= 0) delete constFadeAlphas[abbr];
  }
  if (hoveredConst) {
    constFadeAlphas[hoveredConst] = Math.min(1, (constFadeAlphas[hoveredConst] || 0) + fadeSpeed);
  }
  if (clickedConst && clickedConst !== hoveredConst) {
    constFadeAlphas[clickedConst] = Math.min(1, (constFadeAlphas[clickedConst] || 0) + fadeSpeed);
  }

  // Lazy-allocate star screen buffer
  if (!starScreenBuf || starScreenBuf.length < data.stars.length * 3) {
    starScreenBuf = new Float32Array(data.stars.length * 3);
  }

  // Clear
  ctx.fillStyle = '#050510';
  ctx.fillRect(0, 0, W, H);

  // Background layers
  renderMilkyWay(rc);
  renderTwilight(rc, lstDeg, getCachedSun());
  if (overlays.altAzGrid) renderAltAzGrid(rc);
  if (overlays.eqGrid) renderEqGrid(rc);
  if (overlays.ecliptic) { renderZodiacBand(rc); renderEcliptic(rc); }

  // Sky objects (return screen buffers for hit testing)
  dsoScreenBuf = renderDSOs(rc, data.dsos, selectedObject);
  renderConstellationLines(rc, data.constellations, constFadeAlphas, toggles.constellations);
  starScreenCount = renderStars(rc, data.stars, starScreenBuf);
  renderConstellationHighlight(rc, constFadeAlphas, constByAbbr, data.hip);
  renderSelection(rc, selectedObject);
  renderHorizon(rc);
  renderCardinals(rc);
  planetScreenBuf = renderPlanets(rc, getCachedPlanets());
  renderSun(rc, getCachedSun());
  moonScreenPos = renderMoon(rc, getCachedMoon(), getCachedSun());
  constLabelScreen = renderLabels(rc, data.constellations, data.dsos, constFadeAlphas, toggles.constellations);

  // UI updates
  updateInfo();
  updateClock();
  callUpdatePopup();
}

function frame() {
  render();
  requestAnimationFrame(frame);
}

// --- Init ---

function buildStarNameLookup() {
  starNameLookup = new Map();
  if (data.star_names) {
    for (const hipID of Object.keys(data.star_names)) {
      const pos = data.hip[hipID];
      if (!pos) continue;
      const key = pos[0].toFixed(6) + ',' + pos[1].toFixed(5);
      starNameLookup.set(key, { ...data.star_names[hipID], hipID });
    }
  }
  hipToConst = new Map();
  for (const c of data.constellations) {
    for (const [h1, h2] of c.lines) {
      for (const h of [h1, h2]) {
        const pos = data.hip[String(h)];
        if (pos) hipToConst.set(pos[0].toFixed(6) + ',' + pos[1].toFixed(5), c.abbr);
      }
    }
  }
}

async function init() {
  resize();

  try {
    const resp = await fetch('data/stars.json');
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    data = await resp.json();
  } catch (err) {
    const loadingEl = document.getElementById('loading');
    if (loadingEl) loadingEl.textContent = `failed to load star catalog: ${err.message}`;
    return;
  }

  data.stars.sort((a, b) => a[2] - b[2]);

  for (const c of data.constellations) {
    c.resolvedLines = [];
    for (const pair of c.lines) {
      const s1 = data.hip[String(pair[0])];
      const s2 = data.hip[String(pair[1])];
      if (s1 && s2) c.resolvedLines.push([s1[0], s1[1], s2[0], s2[1]]);
    }
  }

  initMilkyWay(data.milky_way);
  buildStarNameLookup();
  constByAbbr = new Map(data.constellations.map(c => [c.abbr, c]));

  const initJd = (Date.now() + getTimeState().timeOffsetMs) / 86400000 + 2440587.5;
  updateEphemeris(initJd);
  buildSearchIndex(data, getCachedPlanets(), getCachedMoon());
  setupTimeControls();
  setupSearch({
    setViewTarget: (t) => { viewTarget = t; },
    setSelectedObject: (o) => { selectedObject = o; },
    setClickedConst: (c) => { clickedConst = c; },
    getAppState: () => ({ cachedPlanets: getCachedPlanets(), cachedMoon: getCachedMoon(), data, cx, cy }),
  });
  setupInput(
    { view, drag, overlays, toggles, canvas, getSize: () => ({ W, H }) },
    {
      setViewTarget: (t) => { viewTarget = t; },
      setSelectedObject: (o) => { selectedObject = o; },
      setClickedConst: (c) => { clickedConst = c; },
      setHoveredConst: (h) => { hoveredConst = h; },
      onResize: resize,
      getScreenState: () => ({
        starScreenBuf, starScreenCount, planetScreenBuf, moonScreenPos,
        constLabelScreen, dsoScreenBuf, data, hipToConst,
      }),
    },
  );

  const loadingEl = document.getElementById('loading');
  if (loadingEl) {
    loadingEl.classList.add('hidden');
    setTimeout(() => loadingEl.remove(), 800);
  }

  frame();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}
