/**
 * starfield.js — Interactive Star Viewer
 *
 * Real-time night sky from Los Angeles (34.05°N, 118.24°W).
 * Camera-frame projection in horizontal space — flat horizon at all azimuths.
 *
 * Features: star colors, twinkle, type-aware DSOs, coordinate grids,
 * magnitude-based zoom detail, constellation hover/click highlighting,
 * star/planet click-to-inspect, Moon with phase, twilight glow, live LA clock.
 *
 * Data: data/stars.json (generated by scripts/process_stars.py)
 */

import { fovToScale }      from './sky/projection.js';
import { lst, hzToEq, eqToHz } from './sky/time.js';
import { planetPositions, sunPosition, moonPosition } from './sky/planets.js';

// --- Observer (Los Angeles) ---

const LAT_LA  =  34.0522;
const LON_LA  = -118.2437;
const SIN_LAT = Math.sin(LAT_LA * Math.PI / 180);
const COS_LAT = Math.cos(LAT_LA * Math.PI / 180);

// --- Constants ---

const D2R = Math.PI / 180;
const R2D = 180 / Math.PI;

const MAG_BRIGHT = -1.5;
const MAG_DIM    =  6.5;
const R_MAX      =  5.5;   // brightest star radius (CSS px)
const R_MIN      =  0.8;   // dimmest star radius
const A_MAX      =  1.0;
const A_MIN      =  0.15;

const FOV_DEFAULT  =  90;
const FOV_MIN      =  15;
const FOV_MAX      = 150;
const ALT_MIN      = -85;
const ALT_MAX      =  85;

const LABEL_FADE_DEG    =  6;
const BELOW_HORIZON_DIM = 0.35;
const MAG_FADE_BAND     = 0.5;
const OBLIQUITY         = 23.43928;

const CARDINALS = [
  { az:   0, label: 'N' },
  { az:  90, label: 'E' },
  { az: 180, label: 'S' },
  { az: 270, label: 'W' },
];

// --- Accessibility ---
// Light mode: canvas is always dark (astronomy viewer). HTML overlays use inline
// dark styles in starfield_test.html. Portfolio integration (Section 2) will hide
// the canvas entirely when light mode is active.

const reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

// --- B-V Color LUT ---

const COLOR_LUT = buildColorLUT();

function buildColorLUT() {
  const anchors = [
    [-0.33, 155, 176, 255], [-0.17, 170, 191, 255], [0.00, 192, 209, 255],
    [0.15, 212, 225, 255], [0.30, 237, 238, 255], [0.45, 255, 251, 245],
    [0.60, 255, 244, 232], [0.80, 255, 227, 196], [1.00, 255, 210, 161],
    [1.40, 255, 187, 123], [2.00, 255, 160, 100],
  ];
  const lut = new Array(256);
  for (let i = 0; i < 256; i++) {
    const bv = (i / 255) * 2.4 - 0.4;
    let lo = 0, hi = anchors.length - 1;
    for (let j = 0; j < anchors.length - 1; j++) {
      if (bv >= anchors[j][0] && bv <= anchors[j + 1][0]) { lo = j; hi = j + 1; break; }
    }
    if (bv <= anchors[0][0]) { lo = 0; hi = 0; }
    if (bv >= anchors[anchors.length - 1][0]) { lo = anchors.length - 1; hi = lo; }
    const t = lo === hi ? 0 : (bv - anchors[lo][0]) / (anchors[hi][0] - anchors[lo][0]);
    const r = Math.round(anchors[lo][1] + (anchors[hi][1] - anchors[lo][1]) * t);
    const g = Math.round(anchors[lo][2] + (anchors[hi][2] - anchors[lo][2]) * t);
    const b = Math.round(anchors[lo][3] + (anchors[hi][3] - anchors[lo][3]) * t);
    lut[i] = `${r},${g},${b}`;
  }
  return lut;
}

function bvToColor(ci) {
  if (ci == null) return '220,220,255';
  return COLOR_LUT[Math.max(0, Math.min(255, Math.round((ci + 0.4) / 2.4 * 255)))];
}

// --- DOM ---

const canvas   = document.getElementById('sky-canvas');
const ctx      = canvas.getContext('2d');
const infoEl   = document.getElementById('info');
const coordsEl = document.getElementById('cursor-coords');
const clockTimeEl = document.getElementById('clock-time');
const clockDateEl = document.getElementById('clock-date');
const popupEl     = document.getElementById('object-popup');

// --- State ---

let data = null;

const view = { az: 180.0, alt: 45.0, fov: FOV_DEFAULT };
const drag = { active: false, prevX: 0, prevY: 0, startX: 0, startY: 0, startTime: 0 };
const overlays = { altAzGrid: false, eqGrid: false, ecliptic: true };
const toggles  = { constLines: true, constLabels: true };

let selectedObject = null;  // { type, px, py, ra, dec, ... }
let hoveredConst   = null;  // constellation abbr
let clickedConst   = null;  // persisted constellation highlight
let constFadeAlphas = {};    // { abbr: alpha } per-constellation fade values
let _lastFrameTime = performance.now();

// Time controls
let timeOffsetMs = 0;       // offset from real time (ms)
let timeSpeed = 1;          // 0=paused, 1=real, 10/100/1000=fast, negative=rewind
let _lastRealTime = Date.now();
let _prevTimeSpeed = 1;     // for pause/resume toggle
const SPEED_STEPS = [-1000, -100, -10, -1, 0, 1, 10, 100, 1000];

// Animated pan
let viewTarget = null;      // { az, alt } or null — lerp target

// Search
let searchIndex = [];       // [{ name, type, ra, dec, abbr? }]
let searchOpen = false;

let cursorPx = -1, cursorPy = -1;
let W = 0, H = 0, cx = 0, cy = 0;

// Screen position buffers for hit testing (filled each frame)
let starScreenBuf = null;
let starScreenCount = 0;
let planetScreenBuf = [];
let moonScreenPos = null;
let constLabelScreen = [];
let dsoScreenBuf = [];      // [{name, type, px, py, ra, dec, screenR}]

// Star name reverse lookup: "ra,dec" → {name, con, hipID}
let starNameLookup = null;
// HIP ID → constellation abbr (for hover-over-star → highlight constellation)
let hipToConst = null;
// Constellation abbr → constellation object (O(1) lookup)
let constByAbbr = null;

// --- Canvas sizing ---

function resize() {
  const dpr = window.devicePixelRatio || 1;
  W = window.innerWidth;
  H = window.innerHeight;
  canvas.width  = Math.round(W * dpr);
  canvas.height = Math.round(H * dpr);
  canvas.style.width  = W + 'px';
  canvas.style.height = H + 'px';
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  cx = W / 2;
  cy = H / 2;
}

// --- Visual mapping ---

function magToRadius(mag) {
  const t = Math.min(1, Math.max(0, (mag - MAG_BRIGHT) / (MAG_DIM - MAG_BRIGHT)));
  return R_MAX + (R_MIN - R_MAX) * t;
}

function magToAlpha(mag) {
  const t = Math.min(1, Math.max(0, (mag - MAG_BRIGHT) / (MAG_DIM - MAG_BRIGHT)));
  return A_MAX + (A_MIN - A_MAX) * t;
}

function edgeFade(cosAngle) {
  const theta = Math.acos(Math.max(-1, Math.min(1, cosAngle))) * R2D;
  const halfFov = view.fov / 2;
  if (theta >= halfFov) return 0;
  if (theta <= halfFov - LABEL_FADE_DEG) return 1;
  return (halfFov - theta) / LABEL_FADE_DEG;
}

function fovMagLimit(fovDeg) {
  // FOV 150° → mag 4.0 (only brightest), FOV 90° → mag 6.0, FOV 50° → mag 6.6 (all stars), FOV 15° → mag 7.0
  if (fovDeg >= 90) return Math.max(1.0, 6.0 + (fovDeg - 90) * (-2.0 / 60));
  if (fovDeg >= 50) return 6.0 + (90 - fovDeg) * (0.6 / 40);
  return 6.6 + (50 - fovDeg) * (0.4 / 35);
}

function formatRA(ra) {
  const h = Math.floor(ra);
  const m = Math.floor((ra - h) * 60);
  const s = Math.floor(((ra - h) * 60 - m) * 60);
  return `${h}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`;
}

function formatDec(dec) {
  const sign = dec >= 0 ? '+' : '-';
  const d = Math.abs(dec);
  const deg = Math.floor(d);
  const min = Math.floor((d - deg) * 60);
  return `${sign}${deg}° ${String(min).padStart(2,'0')}'`;
}

// ============================================================
// Camera-frame projection
// ============================================================

function buildViewFrame(altDeg, azDeg, lstDeg) {
  const altR = altDeg * D2R, azR = azDeg * D2R;
  const sinAz = Math.sin(azR), cosAz = Math.cos(azR);
  const sinAlt = Math.sin(altR), cosAlt = Math.cos(altR);
  return {
    rX: cosAz, rY: -sinAz,
    uX: -sinAz * sinAlt, uY: -cosAz * sinAlt, uZ: cosAlt,
    fX: sinAz * cosAlt, fY: cosAz * cosAlt, fZ: sinAlt,
    lstDeg,
  };
}

function projectStar(ra, dec, vf) {
  const H = (vf.lstDeg - ra * 15) * D2R;
  const decR = dec * D2R;
  const sd = Math.sin(decR), cd = Math.cos(decR);
  const ch = Math.cos(H), sh = Math.sin(H);
  const xHz = -cd * sh;
  const yHz = COS_LAT * sd - SIN_LAT * cd * ch;
  const zHz = SIN_LAT * sd + COS_LAT * cd * ch;
  const camX = xHz * vf.rX + yHz * vf.rY;
  const camY = xHz * vf.uX + yHz * vf.uY + zHz * vf.uZ;
  const cosA = xHz * vf.fX + yHz * vf.fY + zHz * vf.fZ;
  const D = 1 + cosA;
  if (D < 0.001) return null;
  return { x: camX / D, y: camY / D, cosAngle: cosA, belowHorizon: zHz < 0 };
}

function projectHzPoint(alt, az, vf) {
  const altR = alt * D2R, azR = az * D2R;
  const xHz = Math.cos(altR) * Math.sin(azR);
  const yHz = Math.cos(altR) * Math.cos(azR);
  const zHz = Math.sin(altR);
  const camX = xHz * vf.rX + yHz * vf.rY;
  const camY = xHz * vf.uX + yHz * vf.uY + zHz * vf.uZ;
  const cosA = xHz * vf.fX + yHz * vf.fY + zHz * vf.fZ;
  const D = 1 + cosA;
  if (D < 0.001) return null;
  return { x: camX / D, y: camY / D, cosAngle: cosA };
}

function screenToRaDec(px, py, scale, vf) {
  const x = (px - cx) / scale, y = (cy - py) / scale;
  const rho = Math.sqrt(x * x + y * y);
  if (rho < 1e-10) return hzToEq(view.alt, view.az, vf.lstDeg, LAT_LA);
  const c = 2 * Math.atan(rho);
  const cosC = Math.cos(c), sinC = Math.sin(c);
  const camX = x * sinC / rho, camY = y * sinC / rho, camZ = cosC;
  const xHz = camX * vf.rX + camY * vf.uX + camZ * vf.fX;
  const yHz = camX * vf.rY + camY * vf.uY + camZ * vf.fY;
  const zHz = camY * vf.uZ + camZ * vf.fZ;
  const alt = Math.asin(Math.max(-1, Math.min(1, zHz))) * R2D;
  const az = ((Math.atan2(xHz, yHz) * R2D) + 360) % 360;
  return hzToEq(alt, az, vf.lstDeg, LAT_LA);
}

// ============================================================
// Hit testing
// ============================================================

function findNearestStar(clickX, clickY, threshold) {
  // Weighted hit testing: bright stars have larger effective hit radius,
  // faint stars only selectable when zoomed in (small FOV)
  let bestScore = Infinity, bestIdx = -1;
  const th2 = threshold * threshold;
  for (let i = 0; i < starScreenCount; i++) {
    const bi = i * 3;
    const dx = starScreenBuf[bi] - clickX, dy = starScreenBuf[bi + 1] - clickY;
    const dist2 = dx * dx + dy * dy;
    if (dist2 > th2) continue;
    const si = starScreenBuf[bi + 2];
    const mag = data.stars[si][2];
    // Penalize faint stars: effective distance increases with magnitude
    // Bright stars (mag 0) get no penalty; faint (mag 6+) get 3x distance penalty
    const magPenalty = 1 + Math.max(0, mag - 2) * 0.3;
    const score = dist2 * magPenalty * magPenalty;
    if (score < bestScore) { bestScore = score; bestIdx = i; }
  }
  if (bestIdx < 0) return null;
  const bi = bestIdx * 3;
  const si = starScreenBuf[bi + 2];
  const s = data.stars[si];
  return {
    type: 'star', px: starScreenBuf[bi], py: starScreenBuf[bi + 1],
    mag: s[2], ci: s[3], dist: s[4], spect: s[5], ra: s[0], dec: s[1],
  };
}

function findNearestPlanet(clickX, clickY, threshold) {
  let bestDist = threshold * threshold, best = null;
  for (const p of planetScreenBuf) {
    const dx = p.px - clickX, dy = p.py - clickY;
    const d = dx * dx + dy * dy;
    if (d < bestDist) { bestDist = d; best = p; }
  }
  return best ? { type: 'planet', ...best } : null;
}

function findNearestConstLabel(clickX, clickY, threshold) {
  let bestDist = threshold * threshold, best = null;
  for (const c of constLabelScreen) {
    const dx = c.px - clickX, dy = c.py - clickY;
    const d = dx * dx + dy * dy;
    if (d < bestDist) { bestDist = d; best = c; }
  }
  return best;
}

function findNearestDSO(clickX, clickY, threshold) {
  let bestDist = threshold * threshold, best = null;
  for (const d of dsoScreenBuf) {
    const dx = d.px - clickX, dy = d.py - clickY;
    const dist2 = dx * dx + dy * dy;
    // Use screenR as hit area (at least threshold)
    const hitR = Math.max(d.screenR, threshold);
    if (dist2 < hitR * hitR && dist2 < bestDist) { bestDist = dist2; best = d; }
  }
  return best ? { type: 'dso', ...best } : null;
}

function lookupStarName(ra, dec) {
  if (!starNameLookup) return null;
  return starNameLookup.get(ra.toFixed(6) + ',' + dec.toFixed(5)) || null;
}

// ============================================================
// Render layers
// ============================================================

function renderStars(scale, vf) {
  const cullCos = Math.cos((view.fov / 2 + 10) * D2R);
  const magLimit = fovMagLimit(view.fov);
  const t = performance.now() * 0.001;

  // Lazy-allocate screen buffer (px, py, starIndex per entry)
  if (!starScreenBuf || starScreenBuf.length < data.stars.length * 3) {
    starScreenBuf = new Float32Array(data.stars.length * 3);
  }
  starScreenCount = 0;

  for (let i = 0; i < data.stars.length; i++) {
    const s = data.stars[i];
    const ra = s[0], dec = s[1], mag = s[2], ci = s[3];
    if (mag > magLimit) break;

    const p = projectStar(ra, dec, vf);
    if (!p || p.cosAngle < cullCos) continue;

    const px = cx + p.x * scale;
    const py = cy - p.y * scale;
    const r = magToRadius(mag);
    let a = magToAlpha(mag) * (p.belowHorizon ? BELOW_HORIZON_DIM : 1.0);

    if (mag > magLimit - MAG_FADE_BAND) a *= (magLimit - mag) / MAG_FADE_BAND;

    if (mag < 4.0 && !p.belowHorizon && !reducedMotion) {
      const phase = ((i * 2654435761) >>> 0) & 0xFFFF;
      a *= 0.85 + 0.15 * (
        0.6 * Math.sin(t * 3.7 + phase * 0.001) +
        0.4 * Math.sin(t * 7.1 + phase * 0.0017)
      );
    }

    const rgb = bvToColor(ci);
    ctx.beginPath();
    ctx.arc(px, py, r, 0, Math.PI * 2);
    ctx.fillStyle = `rgba(${rgb},${a.toFixed(3)})`;
    ctx.fill();

    if (mag < 2.0 && !p.belowHorizon) {
      const glowR = r * 5;
      const grad = ctx.createRadialGradient(px, py, r * 0.5, px, py, glowR);
      grad.addColorStop(0, `rgba(${rgb},${(a * 0.35).toFixed(3)})`);
      grad.addColorStop(1, `rgba(${rgb},0)`);
      ctx.beginPath();
      ctx.arc(px, py, glowR, 0, Math.PI * 2);
      ctx.fillStyle = grad;
      ctx.fill();
    }

    // Write to screen buffer for hit testing (px, py, starIndex)
    const bi = starScreenCount * 3;
    starScreenBuf[bi] = px; starScreenBuf[bi+1] = py;
    starScreenBuf[bi+2] = i; // original index into data.stars
    starScreenCount++;
  }
}

function renderConstellationLines(scale, vf) {
  const cullCos = Math.cos((view.fov / 2 + 30) * D2R);

  for (const c of data.constellations) {
    const ha = constFadeAlphas[c.abbr] || 0;
    if (!toggles.constLines && ha <= 0) continue;

    if (ha > 0) {
      const a = 0.35 + (0.65 - 0.35) * ha;
      ctx.strokeStyle = `rgba(${Math.round(255 - 155*ha)},${Math.round(255 - 75*ha)},255,${a.toFixed(3)})`;
      ctx.lineWidth = 1.2 + 1.0 * ha;
    } else {
      ctx.strokeStyle = 'rgba(255,255,255,0.35)';
      ctx.lineWidth = 1.2;
    }

    for (const seg of c.resolvedLines) {
      const p1 = projectStar(seg[0], seg[1], vf);
      const p2 = projectStar(seg[2], seg[3], vf);
      if (!p1 || !p2) continue;
      if (p1.cosAngle < cullCos && p2.cosAngle < cullCos) continue;
      ctx.beginPath();
      ctx.moveTo(cx + p1.x * scale, cy - p1.y * scale);
      ctx.lineTo(cx + p2.x * scale, cy - p2.y * scale);
      ctx.stroke();
    }
  }
}

function renderConstellationHighlight(scale, vf) {
  // Draw highlight rings for ALL constellations that have a non-zero fade alpha
  for (const abbr in constFadeAlphas) {
    const ha = constFadeAlphas[abbr];
    if (ha <= 0.01) continue;
    const con = constByAbbr.get(abbr);
    if (!con) continue;

    const seen = new Set();
    ctx.strokeStyle = `rgba(100,180,255,${(0.8 * ha).toFixed(3)})`;
    ctx.lineWidth = 1.5;

    for (const [h1, h2] of con.lines) {
      for (const h of [h1, h2]) {
        if (seen.has(h)) continue;
        seen.add(h);
        const pos = data.hip[String(h)];
        if (!pos) continue;
        const p = projectStar(pos[0], pos[1], vf);
        if (!p) continue;
        ctx.beginPath();
        ctx.arc(cx + p.x * scale, cy - p.y * scale, 6, 0, Math.PI * 2);
        ctx.stroke();
      }
    }
  }
}

function renderSelection(scale, vf) {
  if (!selectedObject) return;
  const p = projectStar(selectedObject.ra, selectedObject.dec, vf);
  if (!p) return;
  const px = cx + p.x * scale, py = cy - p.y * scale;
  const pulse = reducedMotion ? 1.0 : 0.7 + 0.3 * Math.sin(performance.now() * 0.003);

  ctx.strokeStyle = `rgba(255,220,100,${pulse.toFixed(2)})`;
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.arc(px, py, 8, 0, Math.PI * 2);
  ctx.stroke();

  // Update popup position
  if (popupEl) {
    selectedObject.px = px;
    selectedObject.py = py;
  }
}

function renderDSOs(scale, vf) {
  const cullCos = Math.cos((view.fov / 2 + 5) * D2R);
  dsoScreenBuf = [];

  for (let di = 0; di < data.dsos.length; di++) {
    const d = data.dsos[di];
    const p = projectStar(d.ra, d.dec, vf);
    if (!p || p.cosAngle < cullCos) continue;

    const px = cx + p.x * scale, py = cy - p.y * scale;
    const screenR = Math.max(6, d.size * D2R * scale);
    const b = d.brightness;

    if (d.type === 'nebula') {
      ctx.fillStyle = `rgba(255,180,200,${(b * 0.25).toFixed(3)})`;
      ctx.beginPath(); ctx.arc(px, py, screenR * 0.4, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = `rgba(200,150,180,${(b * 0.10).toFixed(3)})`;
      ctx.beginPath(); ctx.arc(px, py, screenR, 0, Math.PI * 2); ctx.fill();
    } else if (d.type === 'galaxy') {
      const angle = (di * 137.508) * D2R;
      ctx.save(); ctx.translate(px, py); ctx.rotate(angle);
      ctx.fillStyle = `rgba(255,240,200,${(b * 0.20).toFixed(3)})`;
      ctx.beginPath(); ctx.ellipse(0, 0, screenR * 0.6, screenR * 0.25, 0, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = `rgba(255,230,180,${(b * 0.08).toFixed(3)})`;
      ctx.beginPath(); ctx.ellipse(0, 0, screenR, screenR * 0.45, 0, 0, Math.PI * 2); ctx.fill();
      ctx.restore();
    } else if (d.type === 'open_cluster') {
      ctx.fillStyle = `rgba(200,220,255,${(b * 0.35).toFixed(3)})`;
      for (let j = 0; j < 7; j++) {
        const a2 = (j * 137.508 + di * 50) * D2R;
        const r2 = screenR * 0.4 * (0.3 + (j % 3) * 0.35);
        ctx.beginPath(); ctx.arc(px + Math.cos(a2) * r2, py + Math.sin(a2) * r2, 1.5, 0, Math.PI * 2); ctx.fill();
      }
    } else if (d.type === 'globular_cluster') {
      ctx.fillStyle = `rgba(255,240,210,${(b * 0.35).toFixed(3)})`;
      ctx.beginPath(); ctx.arc(px, py, screenR * 0.25, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = `rgba(255,230,200,${(b * 0.12).toFixed(3)})`;
      ctx.beginPath(); ctx.arc(px, py, screenR * 0.6, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = `rgba(240,220,190,${(b * 0.05).toFixed(3)})`;
      ctx.beginPath(); ctx.arc(px, py, screenR, 0, Math.PI * 2); ctx.fill();
    }

    // Selection highlight for DSOs
    if (selectedObject && selectedObject.type === 'dso' && selectedObject.name === d.name) {
      const pulse = reducedMotion ? 1.0 : 0.7 + 0.3 * Math.sin(performance.now() * 0.003);
      ctx.strokeStyle = `rgba(180,180,255,${pulse.toFixed(2)})`;
      ctx.lineWidth = 1.5;
      ctx.beginPath(); ctx.arc(px, py, screenR + 4, 0, Math.PI * 2); ctx.stroke();
    }

    dsoScreenBuf.push({ name: d.name, type: d.type, px, py, ra: d.ra, dec: d.dec, screenR });
  }
}

// --- Milky Way ---

let milkyWayPoints = null;

function buildMilkyWayPoints(waypoints) {
  const wp = (waypoints[0].ra === waypoints[waypoints.length - 1].ra &&
              waypoints[0].dec === waypoints[waypoints.length - 1].dec)
    ? waypoints.slice(0, -1) : waypoints;
  const pts = [], n = wp.length, STEPS = 8;
  for (let i = 0; i < n; i++) {
    const a = wp[(i-1+n)%n], b = wp[i], c = wp[(i+1)%n], d = wp[(i+2)%n];
    for (let s = 0; s < STEPS; s++) {
      const t = s / STEPS, t2 = t*t, t3 = t2*t;
      const ra  = 0.5*((2*b.ra)+(-a.ra+c.ra)*t+(2*a.ra-5*b.ra+4*c.ra-d.ra)*t2+(-a.ra+3*b.ra-3*c.ra+d.ra)*t3);
      const dec = 0.5*((2*b.dec)+(-a.dec+c.dec)*t+(2*a.dec-5*b.dec+4*c.dec-d.dec)*t2+(-a.dec+3*b.dec-3*c.dec+d.dec)*t3);
      const w = b.width + (c.width - b.width) * t;
      const seed = ((i*8+s)*2654435761)>>>0;
      const rA = ((seed&0xFFFF)/0xFFFF-0.5), rD = (((seed>>>16)&0xFFFF)/0xFFFF-0.5);
      pts.push({ra, dec, width: w*0.5});
      pts.push({ra: ra+rA*w*0.02, dec: dec+rD*w*0.3, width: w*0.3});
    }
  }
  return pts;
}

function renderMilkyWay(scale, vf) {
  if (!milkyWayPoints) return;
  ctx.fillStyle = 'rgba(180,180,210,0.008)';
  for (const pt of milkyWayPoints) {
    const p = projectStar(pt.ra, pt.dec, vf);
    if (!p || p.cosAngle < Math.cos((view.fov/2+pt.width)*D2R)) continue;
    const px = cx + p.x * scale, py = cy - p.y * scale;
    ctx.beginPath(); ctx.arc(px, py, pt.width*D2R*scale, 0, Math.PI*2); ctx.fill();
  }
}

// --- Twilight glow ---

function renderTwilight(scale, vf, lstDeg) {
  const sunHz = eqToHz(_cachedSun.ra, _cachedSun.dec, lstDeg, LAT_LA);

  if (sunHz.alt > 0 || sunHz.alt < -18) return;

  const horizonP = projectHzPoint(0, sunHz.az, vf);
  if (!horizonP) return;

  const px = cx + horizonP.x * scale, py = cy - horizonP.y * scale;
  const depth = -sunHz.alt;
  const intensity = Math.max(0, 1 - depth / 18);
  const radius = 200 * intensity + 50;

  const r = depth < 6 ? 255 : Math.round(255 * Math.max(0, 1 - (depth-6)/12));
  const g = depth < 6 ? Math.round(180 - depth * 15) : Math.round(100 * Math.max(0, 1 - (depth-6)/12));
  const b = depth < 6 ? Math.round(100 + depth * 10) : Math.round(160 * Math.max(0, 1 - (depth-6)/12));

  const grad = ctx.createRadialGradient(px, py, 0, px, py, radius);
  grad.addColorStop(0, `rgba(${r},${g},${b},${(intensity * 0.3).toFixed(3)})`);
  grad.addColorStop(1, 'rgba(0,0,0,0)');
  ctx.fillStyle = grad;
  ctx.beginPath(); ctx.arc(px, py, radius, 0, Math.PI*2); ctx.fill();
}

// --- Moon ---

function renderMoon(scale, vf) {
  const moon = _cachedMoon;
  const p = projectStar(moon.ra, moon.dec, vf);
  if (!p) { moonScreenPos = null; return; }

  const alpha = edgeFade(p.cosAngle);
  if (alpha <= 0) { moonScreenPos = null; return; }

  const px = cx + p.x * scale, py = cy - p.y * scale;
  const moonR = 5;

  // Illuminated fraction and phase side
  const k = (1 + Math.cos(moon.elongation * D2R)) / 2;
  // Determine waxing vs waning: moon east of sun = waxing (shadow on right)
  const sunPos = _cachedSun;
  const eastOfSun = ((sunPos.ra - moon.ra) * 15 + 360) % 360 > 180;
  const shadowSign = eastOfSun ? 1 : -1;

  // Draw bright disc
  ctx.beginPath(); ctx.arc(px, py, moonR, 0, Math.PI*2);
  ctx.fillStyle = `rgba(230,230,220,${(alpha * 0.9).toFixed(3)})`;
  ctx.fill();

  // Shadow overlay for phase
  if (k < 0.98) {
    ctx.save();
    ctx.beginPath(); ctx.arc(px, py, moonR, 0, Math.PI*2); ctx.clip();
    const shadowX = px + moonR * (2 * k - 1) * shadowSign;
    ctx.fillStyle = `rgba(5,5,16,${(alpha * 0.85).toFixed(3)})`;
    ctx.beginPath(); ctx.arc(shadowX, py, moonR, 0, Math.PI*2); ctx.fill();
    ctx.restore();
  }

  // Soft glow
  ctx.beginPath(); ctx.arc(px, py, moonR * 3, 0, Math.PI*2);
  const grad = ctx.createRadialGradient(px, py, moonR, px, py, moonR*3);
  grad.addColorStop(0, `rgba(200,200,190,${(alpha*0.15).toFixed(3)})`);
  grad.addColorStop(1, 'rgba(200,200,190,0)');
  ctx.fillStyle = grad; ctx.fill();

  // Label
  ctx.save();
  ctx.textAlign = 'center'; ctx.textBaseline = 'top';
  ctx.font = '11px sans-serif';
  ctx.fillStyle = `rgba(220,220,210,${(alpha*0.8).toFixed(3)})`;
  ctx.fillText('Moon', px, py + moonR + 4);
  ctx.restore();

  // Store for hit testing
  moonScreenPos = { name: 'Moon', px, py, ra: moon.ra, dec: moon.dec,
                    elongation: moon.elongation, illumination: k, screenR: moonR };
}

// --- Grid overlays ---

function drawGridLine(count, getPoint, scale) {
  let penDown = false;
  for (let i = 0; i < count; i++) {
    const p = getPoint(i);
    if (!p || p.cosAngle < 0.01) { penDown = false; continue; }
    const px = cx + p.x * scale, py = cy - p.y * scale;
    if (!penDown) { ctx.moveTo(px, py); penDown = true; }
    else ctx.lineTo(px, py);
  }
}

function renderAltAzGrid(scale, vf) {
  ctx.strokeStyle = 'rgba(100,150,200,0.25)'; ctx.lineWidth = 0.5;
  for (let alt = -80; alt <= 80; alt += 10) {
    if (alt === 0) continue;
    ctx.beginPath(); drawGridLine(181, i => projectHzPoint(alt, i*2, vf), scale); ctx.stroke();
  }
  for (let az = 0; az < 360; az += 15) {
    ctx.beginPath(); drawGridLine(91, i => projectHzPoint(-90+i*2, az, vf), scale); ctx.stroke();
  }
}

function renderEqGrid(scale, vf) {
  for (let dec = -80; dec <= 80; dec += 10) {
    ctx.strokeStyle = dec === 0 ? 'rgba(100,200,150,0.5)' : 'rgba(100,200,150,0.25)';
    ctx.lineWidth = dec === 0 ? 1.0 : 0.5;
    ctx.beginPath(); drawGridLine(181, i => projectStar(i*24/180, dec, vf), scale); ctx.stroke();
  }
  ctx.strokeStyle = 'rgba(100,200,150,0.25)'; ctx.lineWidth = 0.5;
  for (let raH = 0; raH < 24; raH++) {
    ctx.beginPath(); drawGridLine(91, i => projectStar(raH, -90+i*2, vf), scale); ctx.stroke();
  }
}

function renderEcliptic(scale, vf) {
  const oblR = OBLIQUITY * D2R;
  ctx.strokeStyle = 'rgba(200,200,100,0.35)'; ctx.lineWidth = 1.0;
  ctx.setLineDash([6, 4]);
  ctx.beginPath();
  drawGridLine(361, i => {
    const lamR = i * D2R;
    return projectStar(((Math.atan2(Math.sin(lamR)*Math.cos(oblR), Math.cos(lamR))*R2D+360)%360)/15,
                       Math.asin(Math.sin(lamR)*Math.sin(oblR))*R2D, vf);
  }, scale);
  ctx.stroke(); ctx.setLineDash([]);
}

/** Zodiac band — ±9° around the ecliptic where constellations and planets live. */
function renderZodiacBand(scale, vf) {
  const oblR = OBLIQUITY * D2R;
  const BAND_HALF = 9; // degrees above/below ecliptic

  // Draw two parallel lines at ecliptic latitude ±BAND_HALF
  for (const offset of [BAND_HALF, -BAND_HALF]) {
    ctx.strokeStyle = 'rgba(40,120,200,0.18)';
    ctx.lineWidth = 0.8;
    ctx.beginPath();
    drawGridLine(361, i => {
      const lamR = i * D2R;
      // Ecliptic longitude → ecliptic lat offset → equatorial RA/Dec
      const eclLat = offset * D2R;
      const sinLam = Math.sin(lamR), cosLam = Math.cos(lamR);
      const sinB = Math.sin(eclLat), cosB = Math.cos(eclLat);
      // Ecliptic → equatorial rotation
      const x = cosB * cosLam;
      const y = cosB * sinLam * Math.cos(oblR) - sinB * Math.sin(oblR);
      const z = cosB * sinLam * Math.sin(oblR) + sinB * Math.cos(oblR);
      const ra = ((Math.atan2(y, x) * R2D + 360) % 360) / 15;
      const dec = Math.asin(Math.max(-1, Math.min(1, z))) * R2D;
      return projectStar(ra, dec, vf);
    }, scale);
    ctx.stroke();
  }
}

// --- Horizon, Cardinals ---

function renderHorizon(scale, vf) {
  ctx.beginPath(); let penDown = false;
  for (let i = 0; i <= 360; i++) {
    const p = projectHzPoint(0, i%360, vf);
    if (!p || p.cosAngle < 0.01) { penDown = false; continue; }
    const px = cx+p.x*scale, py = cy-p.y*scale;
    if (!penDown) { ctx.moveTo(px, py); penDown = true; } else ctx.lineTo(px, py);
  }
  ctx.strokeStyle = 'rgba(255,255,255,0.55)'; ctx.lineWidth = 1.5; ctx.stroke();
}

function renderPlanets(scale, vf) {
  const cullCos = Math.cos((view.fov / 2 + 5) * D2R);
  const planets = _cachedPlanets;
  planetScreenBuf = [];

  for (const planet of planets) {
    const p = projectStar(planet.ra, planet.dec, vf);
    if (!p || p.cosAngle < cullCos) continue;
    const alpha = edgeFade(p.cosAngle);
    if (alpha <= 0) continue;

    const a = alpha * (p.belowHorizon ? BELOW_HORIZON_DIM : 1.0);
    const px = cx + p.x * scale, py = cy - p.y * scale;
    const r = planet.screenR;

    const grad = ctx.createRadialGradient(px, py, 0, px, py, r*2.5);
    grad.addColorStop(0, `rgba(255,165,0,${(a*0.9).toFixed(3)})`);
    grad.addColorStop(0.5, `rgba(255,140,0,${(a*0.4).toFixed(3)})`);
    grad.addColorStop(1, 'rgba(255,120,0,0)');
    ctx.beginPath(); ctx.arc(px, py, r*2.5, 0, Math.PI*2); ctx.fillStyle = grad; ctx.fill();
    ctx.beginPath(); ctx.arc(px, py, r, 0, Math.PI*2);
    ctx.fillStyle = `rgba(255,180,60,${a.toFixed(3)})`; ctx.fill();

    ctx.save();
    ctx.textAlign = 'center'; ctx.textBaseline = 'top'; ctx.font = '11px sans-serif';
    ctx.fillStyle = `rgba(255,200,100,${(a*0.85).toFixed(3)})`;
    ctx.fillText(planet.name, px, py + r + 4);
    ctx.restore();

    planetScreenBuf.push({ name: planet.name, px, py, ra: planet.ra, dec: planet.dec, screenR: r });
  }
}

function renderCardinals(scale, vf) {
  ctx.font = 'bold 13px monospace'; ctx.textAlign = 'center'; ctx.textBaseline = 'bottom';
  for (const { az, label } of CARDINALS) {
    const p = projectHzPoint(0, az, vf);
    if (!p || p.cosAngle < 0.01) continue;
    const alpha = edgeFade(p.cosAngle);
    if (alpha <= 0) continue;
    const px = cx+p.x*scale, py = cy-p.y*scale;
    ctx.strokeStyle = `rgba(255,255,255,${(0.75*alpha).toFixed(3)})`; ctx.lineWidth = 1.5;
    ctx.beginPath(); ctx.moveTo(px, py-7); ctx.lineTo(px, py+7); ctx.stroke();
    ctx.fillStyle = `rgba(255,255,255,${(0.9*alpha).toFixed(3)})`;
    ctx.fillText(label, px, py-10);
  }
}

function renderLabels(scale, vf) {
  constLabelScreen = [];

  if (toggles.constLabels) {
    ctx.textAlign = 'center'; ctx.textBaseline = 'bottom'; ctx.font = '13px sans-serif';
    for (const c of data.constellations) {
      const p = projectStar(c.label_ra, c.label_dec, vf);
      if (!p) continue;
      const alpha = edgeFade(p.cosAngle);
      if (alpha <= 0) continue;
      const px = cx + p.x * scale, py = cy - p.y * scale;
      const ha = constFadeAlphas[c.abbr] || 0;
      const r = Math.round(255 - 155 * ha), g = Math.round(255 - 75 * ha);
      const a2 = (0.45 + 0.40 * ha) * alpha;
      ctx.fillStyle = `rgba(${r},${g},255,${a2.toFixed(3)})`;
      ctx.fillText(c.name, px, py - 10);
      constLabelScreen.push({ abbr: c.abbr, px, py });
    }
  } else {
    // Still fill constLabelScreen for hover detection even when labels hidden
    for (const c of data.constellations) {
      const p = projectStar(c.label_ra, c.label_dec, vf);
      if (!p) continue;
      if (edgeFade(p.cosAngle) <= 0) continue;
      constLabelScreen.push({ abbr: c.abbr, px: cx + p.x * scale, py: cy - p.y * scale });
    }
  }

  ctx.textBaseline = 'top'; ctx.font = '11px sans-serif';
  for (const d of data.dsos) {
    const p = projectStar(d.ra, d.dec, vf);
    if (!p) continue;
    const alpha = edgeFade(p.cosAngle);
    if (alpha <= 0) continue;
    ctx.fillStyle = `rgba(180,180,255,${(0.40*alpha).toFixed(3)})`;
    ctx.fillText(d.name, cx+p.x*scale, cy-p.y*scale+10);
  }
}

// --- Info popup ---

let _popupTarget = null; // track what's shown to avoid re-rendering every frame

/** Spectral class letter → display color */
function spectColor(spect) {
  if (!spect) return '#aaa';
  const cls = spect.charAt(0).toUpperCase();
  const colors = { O: '#4466ff', B: '#6688ff', A: '#88bbff', F: '#ffffff', G: '#ffee99', K: '#ff9944', M: '#ff4422' };
  return colors[cls] || '#aaa';
}

function formatDist(dist) {
  if (dist == null) return '\u2014';
  if (dist < 100) return dist.toFixed(1) + ' ly';
  return Math.round(dist).toLocaleString() + ' ly';
}

function popupRow(label, value) {
  return `<div class="popup-row"><span class="popup-label">${label}</span><span class="popup-value">${value}</span></div>`;
}

function updatePopup() {
  if (!popupEl) return;

  // Determine what should be shown: selectedObject, clickedConst, or nothing
  const target = selectedObject || (clickedConst ? { type: 'constellation', abbr: clickedConst } : null);

  if (!target) {
    if (_popupTarget) {
      popupEl.classList.remove('visible');
      popupEl.addEventListener('transitionend', () => {
        if (!_popupTarget) popupEl.classList.remove('fade-in');
      }, { once: true });
      _popupTarget = null;
    }
    return;
  }

  // Build content only when target changes
  const targetKey = target.type + ':' + (target.name || target.abbr || target.ra);
  if (_popupTarget !== targetKey) {
    _popupTarget = targetKey;
    let html = '';

    if (target.type === 'star') {
      const info = lookupStarName(target.ra, target.dec);
      const name = info ? info.name : '—';
      const conAbbr = info ? info.con : (hipToConst && hipToConst.get(target.ra.toFixed(6)+','+target.dec.toFixed(5))) || '—';
      const conName = conAbbr !== '—' ? (constByAbbr.get(conAbbr)?.name || conAbbr) : '—';
      const rgb = bvToColor(target.ci);
      const dist = target.dist ?? (info?.dist);
      const spect = target.spect ?? (info?.spect);
      const sColor = spectColor(spect);
      html = `<div class="popup-name">${name !== '—' ? name : 'Star'}</div>`
        + `<div class="popup-type">Star</div>`
        + popupRow('Magnitude', target.mag.toFixed(2))
        + popupRow('Distance', formatDist(dist))
        + popupRow('Spectral Type', spect ? `<span style="color:${sColor}">${spect}</span>` : '—')
        + popupRow('RA/Dec', formatRA(target.ra) + ' / ' + formatDec(target.dec))
        + popupRow('Constellation', conName)
        + popupRow('Color (B-V)', `<span class="popup-swatch" style="background:rgb(${rgb})"></span>${target.ci != null ? target.ci.toFixed(2) : '—'}`);

    } else if (target.type === 'planet') {
      html = `<div class="popup-name">${target.name}</div>`
        + `<div class="popup-type">Planet</div>`
        + popupRow('RA/Dec', formatRA(target.ra) + ' / ' + formatDec(target.dec))
        + popupRow('Distance', '—')
        + popupRow('Magnitude', '—');

    } else if (target.type === 'moon') {
      const pct = Math.round(target.illumination * 100);
      let phaseName = 'New Moon';
      if (pct > 2 && pct < 48) phaseName = 'Waxing Crescent';
      if (pct >= 48 && pct <= 52) phaseName = 'Quarter';
      if (pct > 52 && pct < 98) phaseName = 'Gibbous';
      if (pct >= 98) phaseName = 'Full Moon';
      html = `<div class="popup-name">Moon</div>`
        + `<div class="popup-type">${phaseName} (${pct}% illuminated)</div>`
        + popupRow('RA/Dec', formatRA(target.ra) + ' / ' + formatDec(target.dec));

    } else if (target.type === 'constellation') {
      const con = constByAbbr.get(target.abbr);
      const starCount = con ? new Set(con.lines.flat()).size : 0;
      html = `<div class="popup-name">${con ? con.name : target.abbr}</div>`
        + `<div class="popup-type">Constellation (${target.abbr})</div>`
        + popupRow('Stars', String(starCount))
        + popupRow('Center RA/Dec', con ? formatRA(con.label_ra) + ' / ' + formatDec(con.label_dec) : '—');
    } else if (target.type === 'dso') {
      html = `<div class="popup-name">${target.name}</div>`
        + `<div class="popup-type">Deep Sky Object</div>`
        + popupRow('RA/Dec', formatRA(target.ra) + ' / ' + formatDec(target.dec));
    }

    popupEl.innerHTML = html;
    // Trigger fade-in (double rAF ensures reflow between display:block and opacity change)
    popupEl.classList.add('fade-in');
    requestAnimationFrame(() => requestAnimationFrame(() => popupEl.classList.add('visible')));
  }
}

// --- Clock ---

const clockFmt = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/Los_Angeles',
  hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false,
});
const dateFmt = new Intl.DateTimeFormat('en-US', {
  timeZone: 'America/Los_Angeles',
  year: 'numeric', month: 'short', day: '2-digit', weekday: 'short',
});

let _lastClockSec = -1;
let _lastClockSpeed = null;
function updateClock() {
  if (!clockTimeEl) return;
  const simTime = new Date(Date.now() + timeOffsetMs);
  const s = simTime.getSeconds();
  // Throttle: only update DOM when second changes or speed changes
  if (s === _lastClockSec && timeSpeed === _lastClockSpeed) return;
  _lastClockSec = s;
  _lastClockSpeed = timeSpeed;
  clockTimeEl.textContent = clockFmt.format(simTime);
  clockDateEl.textContent = dateFmt.format(simTime);
  const speedEl = document.getElementById('time-speed');
  if (speedEl) {
    if (timeSpeed === 0) speedEl.textContent = 'Paused';
    else if (timeSpeed === 1) speedEl.textContent = '';
    else speedEl.textContent = `${timeSpeed}\u00d7`;
  }
  // LIVE indicator
  const liveEl = document.getElementById('live-indicator');
  if (liveEl) {
    const isLive = timeSpeed === 1 && Math.abs(timeOffsetMs) < 1000;
    liveEl.classList.toggle('live', isLive);
    liveEl.classList.toggle('not-live', !isLive);
  }
}

// --- Info panel ---

function updateInfo(scale, vf) {
  const lstH = Math.floor(vf.lstDeg / 15);
  const lstM = Math.floor((vf.lstDeg / 15 - lstH) * 60);
  const magLimit = fovMagLimit(view.fov);

  const g = (on, key) => on ? `<span style="color:#4f4">[${key}]</span>` : `<span style="color:#555">[${key}]</span>`;
  infoEl.innerHTML =
    `<b>Star Viewer — Los Angeles</b><br>` +
    `Stars: ${data.meta.star_count} | Mag limit: ${magLimit.toFixed(1)}<br>` +
    `LST: ${lstH}h${String(lstM).padStart(2,'0')}m &nbsp; Az ${view.az.toFixed(1)}° Alt ${view.alt.toFixed(1)}°<br>` +
    `FOV: ${view.fov.toFixed(3)}° &nbsp; ` +
    g(overlays.altAzGrid, 'G') + ' ' + g(overlays.eqGrid, 'Q') + ' ' + g(overlays.ecliptic, 'E') + ' ' +
    g(toggles.constLines, 'L') + ' ' + g(toggles.constLabels, 'K');

  if (cursorPx >= 0) {
    const coords = screenToRaDec(cursorPx, cursorPy, scale, vf);
    coordsEl.textContent =
      `RA ${formatRA(coords.ra)}  Dec ${formatDec(coords.dec)}`;
  }
}

// --- Drag ---

function applyDragRotation(alt, az, dx, dy, degPerPx) {
  const cosAlt = Math.cos(alt * D2R);
  let newAz = ((az - dx * degPerPx / Math.max(cosAlt, 0.15)) % 360 + 360) % 360;
  let newAlt = alt + dy * degPerPx;
  newAlt = Math.max(ALT_MIN, Math.min(ALT_MAX, newAlt));
  return { alt: newAlt, az: newAz };
}

// --- Ephemeris cache (planets/sun/moon recomputed once per minute, not per frame) ---

let _cachedPlanets = null;
let _cachedSun = null;
let _cachedMoon = null;
let _lastEphemJD = 0;

function updateEphemeris(jd) {
  if (jd - _lastEphemJD > 1 / 1440) { // 1 minute in Julian days
    _cachedPlanets = planetPositions(jd);
    _cachedSun = sunPosition(jd);
    _cachedMoon = moonPosition(jd);
    _lastEphemJD = jd;
  }
}

// --- Main render ---

function render() {
  // Time with offset and speed
  const realNow = Date.now();
  const elapsed = realNow - _lastRealTime;
  _lastRealTime = realNow;
  timeOffsetMs += elapsed * (timeSpeed - 1);
  const jd = (realNow + timeOffsetMs) / 86400000 + 2440587.5;

  const lstDeg = lst(jd, LON_LA);
  updateEphemeris(jd);

  // Animate per-frame timing
  const now = performance.now();
  const dt = Math.min((now - _lastFrameTime) / 1000, 0.1);
  _lastFrameTime = now;

  // Animated pan toward target
  if (viewTarget) {
    const speed = 5;
    const dAz = ((viewTarget.az - view.az + 540) % 360) - 180;
    const dAlt = viewTarget.alt - view.alt;
    if (Math.abs(dAz) < 0.1 && Math.abs(dAlt) < 0.1) {
      view.az = viewTarget.az; view.alt = viewTarget.alt;
      viewTarget = null;
    } else {
      view.az = ((view.az + dAz * speed * dt) % 360 + 360) % 360;
      view.alt = Math.max(ALT_MIN, Math.min(ALT_MAX, view.alt + dAlt * speed * dt));
    }
  }

  const vf = buildViewFrame(view.alt, view.az, lstDeg);
  const scale = fovToScale(view.fov, Math.min(cx, cy));
  const fadeSpeed = dt / 0.3;
  const activeAbbr = hoveredConst || clickedConst;
  // Fade in active constellation, fade out all others
  for (const abbr in constFadeAlphas) {
    if (abbr === activeAbbr) continue;
    constFadeAlphas[abbr] -= fadeSpeed;
    if (constFadeAlphas[abbr] <= 0) delete constFadeAlphas[abbr];
  }
  if (activeAbbr) {
    constFadeAlphas[activeAbbr] = Math.min(1, (constFadeAlphas[activeAbbr] || 0) + fadeSpeed);
  }

  ctx.fillStyle = '#050510';
  ctx.fillRect(0, 0, W, H);

  renderMilkyWay(scale, vf);
  renderTwilight(scale, vf, lstDeg);
  if (overlays.altAzGrid) renderAltAzGrid(scale, vf);
  if (overlays.eqGrid) renderEqGrid(scale, vf);
  if (overlays.ecliptic) { renderZodiacBand(scale, vf); renderEcliptic(scale, vf); }
  renderDSOs(scale, vf);
  renderConstellationLines(scale, vf);
  renderStars(scale, vf);
  renderConstellationHighlight(scale, vf);
  renderSelection(scale, vf);
  renderHorizon(scale, vf);
  renderCardinals(scale, vf);
  renderPlanets(scale, vf);
  renderMoon(scale, vf);
  renderLabels(scale, vf);
  updateInfo(scale, vf);
  updateClock();
  updatePopup();
}

function frame() {
  render();
  requestAnimationFrame(frame);
}

// --- Input ---

function syncOverlayButtons() {
  for (const [id, key] of [['btn-altaz','altAzGrid'],['btn-eq','eqGrid'],['btn-ecl','ecliptic']]) {
    const el = document.getElementById(id);
    if (el) el.classList.toggle('active', overlays[key]);
  }
  for (const [id, key] of [['btn-lines','constLines'],['btn-labels','constLabels']]) {
    const el = document.getElementById(id);
    if (el) el.classList.toggle('active', toggles[key]);
  }
}

function handleClick(clickX, clickY) {
  // Priority: Moon > Planets > DSOs > Constellation labels > Stars > Empty sky

  // Check Moon
  if (moonScreenPos) {
    const dx = moonScreenPos.px - clickX, dy = moonScreenPos.py - clickY;
    if (dx*dx + dy*dy < 20*20) {
      selectedObject = { type: 'moon', ...moonScreenPos };
      clickedConst = null;
      return;
    }
  }

  // Check planets
  const planet = findNearestPlanet(clickX, clickY, 20);
  if (planet) { selectedObject = planet; clickedConst = null; return; }

  // Check DSOs (nebulae, galaxies, clusters)
  const dso = findNearestDSO(clickX, clickY, 20);
  if (dso) { selectedObject = dso; clickedConst = null; return; }

  // Check constellation labels (priority over faint stars)
  const cl = findNearestConstLabel(clickX, clickY, 30);
  if (cl) { clickedConst = cl.abbr; selectedObject = null; return; }

  // Check stars (bright stars weighted higher via findNearestStar)
  const star = findNearestStar(clickX, clickY, 15);
  if (star) {
    selectedObject = star;
    const key = star.ra.toFixed(6) + ',' + star.dec.toFixed(5);
    clickedConst = (hipToConst && hipToConst.get(key)) || null;
    return;
  }

  // Deselect
  selectedObject = null;
  clickedConst = null;
}

function setupInput() {
  canvas.style.cursor = 'grab';

  canvas.addEventListener('mousedown', (e) => {
    drag.active = true;
    drag.prevX = e.clientX; drag.prevY = e.clientY;
    drag.startX = e.clientX; drag.startY = e.clientY;
    drag.startTime = performance.now();
    viewTarget = null; // cancel animated pan on drag
    canvas.style.cursor = 'grabbing';
  });

  window.addEventListener('mousemove', (e) => {
    cursorPx = e.clientX; cursorPy = e.clientY;

    if (!drag.active) {
      // Hover: check nearest star for constellation membership, then labels
      let found = null;
      const nearStar = findNearestStar(cursorPx, cursorPy, 20);
      if (nearStar && hipToConst) {
        const key = nearStar.ra.toFixed(6) + ',' + nearStar.dec.toFixed(5);
        found = hipToConst.get(key) || null;
      }
      if (!found) {
        const cl = findNearestConstLabel(cursorPx, cursorPy, 50);
        found = cl ? cl.abbr : null;
      }
      hoveredConst = found;
      return;
    }

    const dx = e.clientX - drag.prevX, dy = e.clientY - drag.prevY;
    const degPerPx = view.fov / Math.min(W, H);
    const nv = applyDragRotation(view.alt, view.az, dx, dy, degPerPx);
    view.alt = nv.alt; view.az = nv.az;
    drag.prevX = e.clientX; drag.prevY = e.clientY;
  });

  window.addEventListener('mouseup', (e) => {
    const wasDrag = drag.active;
    drag.active = false;
    canvas.style.cursor = 'grab';

    // Click detection: small displacement + short duration
    if (wasDrag) {
      const dx = e.clientX - drag.startX, dy = e.clientY - drag.startY;
      const dt = performance.now() - drag.startTime;
      if (Math.abs(dx) < 5 && Math.abs(dy) < 5 && dt < 300) {
        handleClick(e.clientX, e.clientY);
      }
    }
  });

  canvas.addEventListener('wheel', (e) => {
    e.preventDefault();
    let delta = e.deltaY;
    if (e.deltaMode === 1) delta *= 30;
    if (e.deltaMode === 2) delta *= 300;
    view.fov = Math.max(FOV_MIN, Math.min(FOV_MAX, view.fov * Math.pow(1.0003, delta)));
  }, { passive: false });

  // Keyboard shortcuts
  window.addEventListener('keydown', (e) => {
    // Search bar intercepts keys when open
    if (searchOpen && e.key !== 'Escape') return;

    // Grid/overlay toggles
    if (e.key === 'g' || e.key === 'G') { overlays.altAzGrid = !overlays.altAzGrid; syncOverlayButtons(); }
    if (e.key === 'q' || e.key === 'Q') { overlays.eqGrid = !overlays.eqGrid; syncOverlayButtons(); }
    if (e.key === 'e' || e.key === 'E') { overlays.ecliptic = !overlays.ecliptic; syncOverlayButtons(); }
    if (e.key === 'l' || e.key === 'L') { toggles.constLines = !toggles.constLines; syncOverlayButtons(); }
    if (e.key === 'k' || e.key === 'K') { toggles.constLabels = !toggles.constLabels; syncOverlayButtons(); }

    // Arrow key panning
    const PAN_DEG = 2;
    if (e.key === 'ArrowUp')    { viewTarget = null; const nv = applyDragRotation(view.alt, view.az, 0, -1, PAN_DEG); view.alt = nv.alt; e.preventDefault(); }
    if (e.key === 'ArrowDown')  { viewTarget = null; const nv = applyDragRotation(view.alt, view.az, 0, 1, PAN_DEG); view.alt = nv.alt; e.preventDefault(); }
    if (e.key === 'ArrowLeft')  { viewTarget = null; const nv = applyDragRotation(view.alt, view.az, -1, 0, PAN_DEG); view.az = nv.az; e.preventDefault(); }
    if (e.key === 'ArrowRight') { viewTarget = null; const nv = applyDragRotation(view.alt, view.az, 1, 0, PAN_DEG); view.az = nv.az; e.preventDefault(); }
    if (e.key === '+' || e.key === '=') view.fov = Math.max(FOV_MIN, view.fov * 0.95);
    if (e.key === '-') view.fov = Math.min(FOV_MAX, view.fov * 1.05);

    // Search
    if (e.key === '/') { e.preventDefault(); openSearch(); }
    if (e.key === 'Escape') { if (searchOpen) closeSearch(); else { selectedObject = null; clickedConst = null; } }

    // Time controls
    if (e.key === ' ') { e.preventDefault(); togglePause(); }
  });

  // Button wiring
  for (const [id, obj, key] of [
    ['btn-altaz', overlays, 'altAzGrid'], ['btn-eq', overlays, 'eqGrid'], ['btn-ecl', overlays, 'ecliptic'],
    ['btn-lines', toggles, 'constLines'], ['btn-labels', toggles, 'constLabels'],
  ]) {
    const el = document.getElementById(id);
    if (el) el.addEventListener('click', () => { obj[key] = !obj[key]; syncOverlayButtons(); });
  }

  // Touch
  let lastTouchDist = null, lastTouchX = null, lastTouchY = null;
  let touchStartX = 0, touchStartY = 0, touchStartTime = 0;

  canvas.addEventListener('touchstart', (e) => {
    e.preventDefault();
    if (e.touches.length === 1) {
      lastTouchX = e.touches[0].clientX; lastTouchY = e.touches[0].clientY;
      touchStartX = lastTouchX; touchStartY = lastTouchY;
      touchStartTime = performance.now();
      lastTouchDist = null;
    } else if (e.touches.length === 2) {
      lastTouchDist = Math.hypot(
        e.touches[0].clientX - e.touches[1].clientX,
        e.touches[0].clientY - e.touches[1].clientY,
      );
    }
  }, { passive: false });

  canvas.addEventListener('touchmove', (e) => {
    e.preventDefault();
    if (e.touches.length === 1 && lastTouchX !== null) {
      const dx = e.touches[0].clientX - lastTouchX, dy = e.touches[0].clientY - lastTouchY;
      const degPerPx = view.fov / Math.min(W, H);
      const nv = applyDragRotation(view.alt, view.az, dx, dy, degPerPx);
      view.alt = nv.alt; view.az = nv.az;
      lastTouchX = e.touches[0].clientX; lastTouchY = e.touches[0].clientY;
    } else if (e.touches.length === 2 && lastTouchDist !== null) {
      const dist = Math.hypot(
        e.touches[0].clientX - e.touches[1].clientX,
        e.touches[0].clientY - e.touches[1].clientY,
      );
      view.fov = Math.max(FOV_MIN, Math.min(FOV_MAX, view.fov * lastTouchDist / dist));
      lastTouchDist = dist;
    }
  }, { passive: false });

  canvas.addEventListener('touchend', (e) => {
    if (e.touches.length < 2) lastTouchDist = null;
    if (e.touches.length < 1) {
      // Tap detection
      const dx = lastTouchX - touchStartX, dy = lastTouchY - touchStartY;
      const dt = performance.now() - touchStartTime;
      if (Math.abs(dx) < 10 && Math.abs(dy) < 10 && dt < 300) {
        handleClick(touchStartX, touchStartY);
      }
      lastTouchX = null; lastTouchY = null;
    }
  }, { passive: false });

  window.addEventListener('resize', resize);
}

// --- Time Controls ---

function togglePause() {
  if (timeSpeed === 0) {
    timeSpeed = _prevTimeSpeed || 1;
    _lastRealTime = Date.now(); // prevent stale elapsed accumulation on resume
  } else {
    _prevTimeSpeed = timeSpeed;
    timeSpeed = 0;
  }
}

function changeSpeed(dir) {
  const wasPaused = timeSpeed === 0;
  const idx = SPEED_STEPS.indexOf(timeSpeed);
  if (idx === -1) return; // safety: current speed not in steps
  const next = idx + dir;
  if (next >= 0 && next < SPEED_STEPS.length) timeSpeed = SPEED_STEPS[next];
  if (wasPaused && timeSpeed !== 0) _lastRealTime = Date.now();
}

function resetTime() {
  timeOffsetMs = 0; timeSpeed = 1; _lastRealTime = Date.now();
}

function setupTimeControls() {
  const btnRew = document.getElementById('btn-rewind');
  const btnPause = document.getElementById('btn-pause');
  const btnFwd = document.getElementById('btn-forward');
  const btnNow = document.getElementById('btn-now');
  if (btnRew) btnRew.addEventListener('click', () => changeSpeed(-1));
  if (btnPause) btnPause.addEventListener('click', togglePause);
  if (btnFwd) btnFwd.addEventListener('click', () => changeSpeed(1));
  if (btnNow) btnNow.addEventListener('click', resetTime);
}

// --- Search ---

function buildSearchIndex() {
  searchIndex = [];
  // Constellations
  for (const c of data.constellations) {
    searchIndex.push({ name: c.name, type: 'constellation', ra: c.label_ra, dec: c.label_dec, abbr: c.abbr });
  }
  // Named stars
  if (data.star_names) {
    for (const hipID of Object.keys(data.star_names)) {
      const info = data.star_names[hipID];
      const pos = data.hip[hipID];
      if (pos) searchIndex.push({ name: info.name, type: 'star', ra: pos[0], dec: pos[1], hipID });
    }
  }
  // Planets + Moon (use cached positions)
  if (_cachedPlanets) {
    for (const p of _cachedPlanets) searchIndex.push({ name: p.name, type: 'planet', ra: p.ra, dec: p.dec });
  }
  if (_cachedMoon) searchIndex.push({ name: 'Moon', type: 'moon', ra: _cachedMoon.ra, dec: _cachedMoon.dec });
  // DSOs
  for (const d of data.dsos) {
    searchIndex.push({ name: d.name, type: 'dso', ra: d.ra, dec: d.dec });
  }
}

let _searchMatches = [];   // current search results for arrow nav
let _searchSelIdx = -1;    // selected index in results (-1 = none)

function openSearch() {
  const panel = document.getElementById('search-panel');
  const input = document.getElementById('search-input');
  if (!panel || !input) return;
  searchOpen = true;
  panel.classList.add('visible');
  input.value = '';
  input.focus();
  _searchMatches = [];
  _searchSelIdx = -1;
  updateSearchResults('');
}

function closeSearch() {
  const panel = document.getElementById('search-panel');
  if (!panel) return;
  searchOpen = false;
  panel.classList.remove('visible');
  _searchMatches = [];
  _searchSelIdx = -1;
}

function updateSearchResults(query) {
  const resultsEl = document.getElementById('search-results');
  if (!resultsEl) return;
  _searchSelIdx = -1;
  if (!query) { resultsEl.innerHTML = ''; _searchMatches = []; return; }

  const q = query.toLowerCase();
  _searchMatches = searchIndex
    .filter(e => e.name.toLowerCase().includes(q))
    .sort((a, b) => {
      const aStart = a.name.toLowerCase().startsWith(q) ? 0 : 1;
      const bStart = b.name.toLowerCase().startsWith(q) ? 0 : 1;
      return aStart - bStart;
    })
    .slice(0, 8);

  renderSearchResults(resultsEl);
}

function renderSearchResults(resultsEl) {
  resultsEl.innerHTML = _searchMatches.map((m, i) =>
    `<div class="search-result${i === _searchSelIdx ? ' selected' : ''}" data-idx="${i}">` +
    `<span class="sr-type">${m.type === 'constellation' ? '*' : m.type === 'planet' ? 'P' : m.type === 'moon' ? 'M' : '.'}</span>` +
    `<span class="sr-name">${m.name}</span>` +
    `<span class="sr-label">${m.type}</span>` +
    `</div>`
  ).join('');

  resultsEl.querySelectorAll('.search-result').forEach((el, i) => {
    el.addEventListener('click', () => navigateToResult(_searchMatches[i]));
  });
}

function navigateToResult(result) {
  closeSearch();

  // Convert RA/Dec to current alt/az for pan target
  const realNow = Date.now();
  const jd = (realNow + timeOffsetMs) / 86400000 + 2440587.5;
  const lstDeg = lst(jd, LON_LA);
  const hz = eqToHz(result.ra, result.dec, lstDeg, LAT_LA);

  // Clamp target alt to visible range
  const targetAlt = Math.max(ALT_MIN, Math.min(ALT_MAX, hz.alt));
  viewTarget = { az: hz.az, alt: targetAlt };

  // Select the object after navigation
  if (result.type === 'constellation') {
    clickedConst = result.abbr;
    selectedObject = null;
  } else if (result.type === 'star') {
    const pos = data.hip[result.hipID];
    if (pos) {
      selectedObject = { type: 'star', ra: pos[0], dec: pos[1], mag: 0, ci: null, dist: null, spect: null, px: cx, py: cy };
      for (const s of data.stars) {
        if (Math.abs(s[0] - pos[0]) < 0.0001 && Math.abs(s[1] - pos[1]) < 0.0001) {
          selectedObject.mag = s[2]; selectedObject.ci = s[3]; selectedObject.dist = s[4]; selectedObject.spect = s[5]; break;
        }
      }
    }
    clickedConst = null;
  } else if (result.type === 'planet') {
    // Use live cached position (planets move, search index may be stale)
    const live = _cachedPlanets?.find(p => p.name === result.name);
    const ra = live?.ra ?? result.ra, dec = live?.dec ?? result.dec;
    selectedObject = { type: 'planet', name: result.name, ra, dec, px: cx, py: cy };
    // Re-compute pan target with live position
    const hzLive = eqToHz(ra, dec, lstDeg, LAT_LA);
    viewTarget = { az: hzLive.az, alt: Math.max(ALT_MIN, Math.min(ALT_MAX, hzLive.alt)) };
    clickedConst = null;
  } else if (result.type === 'moon') {
    const ra = _cachedMoon?.ra ?? result.ra, dec = _cachedMoon?.dec ?? result.dec;
    selectedObject = { type: 'moon', name: 'Moon', ra, dec,
                       illumination: _cachedMoon ? (1 + Math.cos(_cachedMoon.elongation * D2R)) / 2 : 0.5,
                       elongation: _cachedMoon?.elongation || 0, px: cx, py: cy };
    const hzLive = eqToHz(ra, dec, lstDeg, LAT_LA);
    viewTarget = { az: hzLive.az, alt: Math.max(ALT_MIN, Math.min(ALT_MAX, hzLive.alt)) };
    clickedConst = null;
  } else if (result.type === 'dso') {
    selectedObject = { type: 'dso', name: result.name, ra: result.ra, dec: result.dec, px: cx, py: cy };
    clickedConst = null;
  }
}

function setupSearch() {
  const input = document.getElementById('search-input');
  if (!input) return;
  input.addEventListener('input', () => updateSearchResults(input.value));
  input.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') { closeSearch(); e.stopPropagation(); }
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (_searchMatches.length > 0) {
        _searchSelIdx = Math.min(_searchSelIdx + 1, _searchMatches.length - 1);
        renderSearchResults(document.getElementById('search-results'));
      }
    }
    if (e.key === 'ArrowUp') {
      e.preventDefault();
      if (_searchSelIdx > 0) {
        _searchSelIdx--;
        renderSearchResults(document.getElementById('search-results'));
      }
    }
    if (e.key === 'Enter') {
      const idx = _searchSelIdx >= 0 ? _searchSelIdx : 0;
      if (_searchMatches[idx]) navigateToResult(_searchMatches[idx]);
    }
  });

  // Search button (toggle)
  const searchBtn = document.getElementById('search-btn');
  if (searchBtn) searchBtn.addEventListener('click', () => {
    if (searchOpen) closeSearch(); else openSearch();
  });

  // Click outside search closes it
  const searchPanel = document.getElementById('search-panel');
  document.addEventListener('click', (e) => {
    if (searchOpen && searchBtn && searchPanel &&
        !searchBtn.contains(e.target) && !searchPanel.contains(e.target)) {
      closeSearch();
    }
  });

  // Overlay menu toggle
  const menuToggle = document.getElementById('menu-toggle');
  const overlayMenu = document.getElementById('overlay-menu');
  if (menuToggle && overlayMenu) {
    menuToggle.addEventListener('click', () => overlayMenu.classList.toggle('visible'));
    // Close menu when clicking outside
    document.addEventListener('click', (e) => {
      if (!menuToggle.contains(e.target) && !overlayMenu.contains(e.target)) {
        overlayMenu.classList.remove('visible');
      }
    });
  }
}

// --- Init ---

function buildStarNameLookup() {
  starNameLookup = new Map();
  if (data.star_names) {
    for (const hipID of Object.keys(data.star_names)) {
      const pos = data.hip[hipID];
      if (!pos) continue;
      const key = pos[0].toFixed(6) + ',' + pos[1].toFixed(5);
      starNameLookup.set(key, { ...data.star_names[hipID], hipID });
    }
  }
  // Build ra,dec → constellation abbr for all constellation member stars
  hipToConst = new Map();
  for (const c of data.constellations) {
    for (const [h1, h2] of c.lines) {
      for (const h of [h1, h2]) {
        const pos = data.hip[String(h)];
        if (pos) hipToConst.set(pos[0].toFixed(6) + ',' + pos[1].toFixed(5), c.abbr);
      }
    }
  }
}

async function init() {
  resize();

  try {
    const resp = await fetch('data/stars.json');
    if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
    data = await resp.json();
  } catch (err) {
    const loadingEl = document.getElementById('loading');
    if (loadingEl) loadingEl.textContent = `failed to load star catalog: ${err.message}`;
    return;
  }

  data.stars.sort((a, b) => a[2] - b[2]);

  for (const c of data.constellations) {
    c.resolvedLines = [];
    for (const pair of c.lines) {
      const s1 = data.hip[String(pair[0])];
      const s2 = data.hip[String(pair[1])];
      if (s1 && s2) c.resolvedLines.push([s1[0], s1[1], s2[0], s2[1]]);
    }
  }

  milkyWayPoints = buildMilkyWayPoints(data.milky_way);
  buildStarNameLookup();
  constByAbbr = new Map(data.constellations.map(c => [c.abbr, c]));

  // Initialize ephemeris so search index has planet positions
  const initJd = (Date.now() + timeOffsetMs) / 86400000 + 2440587.5;
  updateEphemeris(initJd);
  buildSearchIndex();
  setupTimeControls();
  setupSearch();

  setupInput();
  syncOverlayButtons();

  const loadingEl = document.getElementById('loading');
  if (loadingEl) {
    loadingEl.classList.add('hidden');
    setTimeout(() => loadingEl.remove(), 800);
  }

  frame();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}
